// Every user-facing string for Quizoma Studio (web-v2), in one place.
// Rule names and their warnings use the app's own wording (res/values/strings.xml, cq_*), so a
// setting reads the same on the web and on the phone.

export const S = {
  // ── App-wide ──
  APP_NAME: "Quizoma",
  STUDIO: "Studio",
  BETA: "Beta",
  BETA_NOTE: "Test mode — these are your real quizzes, and changes show up in the app.",
  ERR_SIGN_IN_FAILED: "Couldn't sign in. Please try again.",
  SIGN_IN: "Continue with Google",
  SIGN_OUT: "Sign out",
  LOADING: "Loading…",
  CANCEL: "Cancel",
  CLOSE: "Close",
  DELETE: "Delete",
  DUPLICATE: "Duplicate",
  EDIT: "Edit",
  BACK: "Back",
  RETRY: "Try again",
  ADD: "Add",
  CLEAR: "Clear",
  REMOVE: "Remove",
  REMOVE_NAMED: "Remove {name}",
  UNDO: "Undo",
  REDO: "Redo",
  UNDONE: "Undone",
  COPIED: "Copied",
  CODE_COPIED: "Code copied",
  LINK_COPIED: "Join link copied",
  ERR_COPY_FAILED: "Couldn't copy — select it and copy by hand.",
  MORE_ACTIONS: "More actions",
  SOON: "Soon",
  JUST_NOW: "just now",
  MIN_AGO: "{n} min ago",
  HOURS_AGO: "{n} h ago",
  SECONDS: "seconds",
  SECONDS_SHORT: "{n}s",
  ANONYMOUS: "Anonymous",
  UNTITLED_QUIZ: "Untitled quiz",
  UNTITLED_QUESTION: "Untitled question",
  OWNER: "Owner",
  SHORTCUTS: "Keyboard shortcuts",
  SHOW_ME: "Show me",

  // ── Navigation / shell ──
  NAV_LABEL: "Main",
  NAV_DASHBOARD: "My quizzes",
  NAV_GRADING: "Marking",
  NAV_NEW: "New",
  BREADCRUMB: "Breadcrumb",
  COLLAPSE_SIDEBAR: "Collapse sidebar",

  // ── Sign-in gate ──
  GATE_TITLE: "Welcome to Quizoma Studio",
  GATE_BODY: "Build quizzes, see results and mark answers on a big screen. Sign in with the same Google account you use in the Quizoma app.",
  GATE_NOTE: "Everything here is the same data as your app — quizzes you make here show up on your phone.",

  // ── Dashboard ──
  MY_QUIZZES: "My quizzes",
  NEW_QUIZ: "New quiz",
  OVERVIEW: "Overview",
  GOOD_MORNING: "Good morning",
  GOOD_AFTERNOON: "Good afternoon",
  GOOD_EVENING: "Good evening",
  DASH_SUBTITLE: "Here's what's happening with your quizzes.",
  STAT_QUIZZES: "Quizzes",
  STAT_LIVE: "Live now",
  STAT_PARTICIPANTS: "Participants",
  STAT_TO_MARK: "Waiting to mark",
  FILTER_ALL: "All",
  FILTER_LIVE: "Live",
  FILTER_DRAFTS: "Drafts",
  FILTER_SCHEDULED: "Scheduled",
  FILTER_ENDED: "Ended",
  FILTER_ARCHIVED: "Archived",
  SEARCH_QUIZZES: "Search by title, group or code",
  SORT_BY: "Sort by",
  SORT_NEWEST: "Newest first",
  SORT_OLDEST: "Oldest first",
  SORT_DRAFTS_FIRST: "Drafts first",
  SORT_MOST_QUESTIONS: "Most questions",
  SORT_LEAST_QUESTIONS: "Fewest questions",
  SORT_SCORE_HIGH: "Highest score",
  SORT_SCORE_LOW: "Lowest score",
  SORT_NAME: "Name A–Z",
  EMPTY_TITLE: "No quizzes yet",
  EMPTY_BODY: "Create your first quiz and share the code with your class. It works in the Quizoma app and on the web.",
  CREATE_FIRST_QUIZ: "Create your first quiz",
  NO_MATCHES_TITLE: "Nothing matches",
  NO_MATCHES_BODY: "Try another filter or search.",
  STATUS_DRAFT: "Draft",
  STATUS_LIVE: "Live",
  STATUS_PUBLISHED: "Published",
  STATUS_ENDED: "Ended",
  STATUS_ARCHIVED: "Archived",
  STATUS_SCHEDULED_AT: "Starts {when}",
  STATUS_READ_ONLY: "Read-only",
  STATUS_TO_MARK: "To mark",
  STATUS_GRADED: "Graded",
  CREATED_ON: "Created {date}",
  QUESTION_COUNT_ONE: "1 question",
  QUESTION_COUNT_MANY: "{n} questions",
  PARTICIPANT_ONE: "1 participant",
  PARTICIPANT_MANY: "{n} participants",
  CODE_AFTER_PUBLISH: "Share code appears once published",
  COPY_CODE: "Copy code",
  COPY_LINK: "Copy join link",
  VIEW_RESULTS: "Results",
  PUBLISH: "Publish",
  ARCHIVE: "Archive",
  UNARCHIVE: "Unarchive",
  N_TO_MARK: "{n} to mark",
  COPY_SUFFIX: " (Copy)",
  CONFIRM_DELETE_TITLE: "Delete this quiz?",
  CONFIRM_DELETE_BODY_NAMED: "“{title}”, its questions and every attempt on it will be removed for everyone. This can't be undone.",
  CONFIRM_PUBLISH_TITLE: "Publish this quiz?",
  CONFIRM_PUBLISH_BODY: "People can join with its share code as soon as it's published. A published quiz can't go back to being a draft — you can archive it later instead.",
  PUBLISH_NEEDS_QUESTIONS: "Add at least one question before publishing.",
  PUBLISH_NEEDS_FIXES: "A few things need fixing first — opening the quiz.",
  QUIZ_DELETED: "Quiz deleted",
  QUIZ_DUPLICATED: "Quiz duplicated",
  QUIZ_PUBLISHED: "Quiz published",
  QUIZ_ARCHIVED: "Quiz archived",
  QUIZ_UNARCHIVED: "Quiz restored",
  LIMIT_REACHED_QUIZZES: "You've reached your limit of {n} quizzes. Delete one to make room.",
  CREATE_DISABLED: "Creating quizzes is paused for maintenance right now. Please try again shortly.",

  // ── Builder ──
  NEW_QUIZ_TITLE: "New quiz",
  EDIT_QUIZ_TITLE: "Edit quiz",
  EDIT_QUIZ: "Edit quiz",
  QUIZ_TITLE_LABEL: "Quiz title",
  QUIZ_TITLE_PLACEHOLDER: "Untitled quiz — give it a name",
  QUESTIONS: "Questions",
  QUESTION: "Question",
  QUESTION_EDITOR: "Question editor",
  SETTINGS: "Settings",
  TAB_QUESTION: "Question",
  TAB_QUIZ: "Quiz settings",
  ADD_QUESTION: "Add question",
  OUTLINE_EMPTY: "No questions yet.",
  NO_QUESTIONS_TITLE: "Add your first question",
  NO_QUESTIONS_BODY: "Pick a type to start. You can change it later. Tip: press 1–6.",
  NO_QUESTIONS_LOCKED: "This quiz has no questions.",
  QUESTION_LIMIT_REACHED: "This quiz is at its limit of {n} questions.",
  SELECT_A_QUESTION: "Select a question to see its settings.",
  HAS_PROBLEMS: "Needs attention",
  QUESTION_N_OF: "Question {n} of {total}",
  QUESTION_TYPE: "Question type",
  QUESTION_TEXT_LABEL: "Question",
  QUESTION_TEXT_PLACEHOLDER: "What do you want to ask?",
  DUPLICATE_QUESTION: "Duplicate question",
  DELETE_QUESTION: "Delete question",
  MOVE_UP: "Move up",
  MOVE_DOWN: "Move down",
  QUESTION_DELETED: "Question deleted",
  QUESTION_DUPLICATED: "Question duplicated",
  CHANGE_TYPE_TITLE: "Change the question type?",
  CHANGE_TYPE_BODY: "Switching to {type} drops answers that don't fit it. You can undo with Ctrl+Z.",
  CHANGE_TYPE_CONFIRM: "Change type",
  TYPE_SINGLE: "Single choice",
  TYPE_SINGLE_SUB: "One right answer",
  TYPE_MULTIPLE: "Multiple correct",
  TYPE_MULTIPLE_SUB: "Tick every right answer",
  TYPE_TRUE_FALSE: "True / False",
  TYPE_TRUE_FALSE_SUB: "Quick yes-or-no check",
  TYPE_WRITTEN: "Written answer",
  TYPE_WRITTEN_SUB: "They type the answer",
  TYPE_FILL_BLANK: "Fill in the blanks",
  TYPE_FILL_BLANK_SUB: "Gaps in a sentence",
  TYPE_POLL: "Poll",
  TYPE_POLL_SUB: "Opinions, no right answer",
  TYPE_AUDIO: "Audio",
  TYPE_VIDEO: "Video",

  OPTIONS_LABEL: "Answer options",
  POLL_CHOICES_LABEL: "Choices",
  ADD_OPTION: "Add option",
  REMOVE_OPTION: "Remove option",
  OPTION_PLACEHOLDER: "Option {n}",
  OPTION_LIMIT_REACHED: "At most {n} options.",
  OPTIONS_PASTED: "Added {n} options from the paste",
  MARK_AS_CORRECT: "Mark as correct",
  MARK_CORRECT_HINT: "Click the circle next to the right answer.",
  MARK_CORRECT_HINT_MULTI: "Tick every right answer.",
  CORRECT_OPTIONAL_MANUAL: "You're marking this quiz yourself, so marking a right answer is optional.",
  ACCEPT_ANY_CORRECT_LABEL: "Any one correct answer is enough",
  ACCEPT_ANY_CORRECT_SUB: "As long as no wrong option is ticked.",
  ACCEPT_ANY_NEEDS_TWO: "Mark at least two right answers to use this.",

  WRITTEN_ANSWER_LABEL: "Expected answer",
  WRITTEN_ANSWER_PLACEHOLDER: "The answer you're looking for",
  WRITTEN_ANSWER_HINT: "Answers are checked against this using the rules below.",
  WRITTEN_ANSWER_HINT_MANUAL: "Optional — you're marking this quiz yourself. It's shown to you as the key while marking.",
  CHECKING_LABEL: "Answer checking",
  MATCH_MODES_LABEL: "How to compare",
  MATCH_MODES_HINT: "Exact and Case-sensitive work alone. Smart match, Keywords and Number can be combined.",
  MODE_SMART: "Smart match",
  MODE_SMART_SUB: "Forgives small typos",
  MODE_EXACT: "Exact",
  MODE_EXACT_SUB: "Same words; case & punctuation ignored",
  MODE_CASE: "Case-sensitive",
  MODE_CASE_SUB: "Capital letters must match",
  MODE_KEYWORDS: "Keywords",
  MODE_KEYWORDS_SUB: "Must mention key words",
  MODE_NUMBER: "Number",
  MODE_NUMBER_SUB: "7 = seven = 7.0",
  STRICTNESS_LABEL: "Strictness",
  STRICTNESS_LENIENT: "More forgiving",
  STRICTNESS_STRICT: "Stricter",
  KEYWORDS_LABEL: "Keywords",
  KEYWORD_PLACEHOLDER: "Type a keyword and press Enter",
  NO_KEYWORDS: "No keywords yet.",
  KEYWORD_COVERAGE: "How many must appear",
  COVERAGE_ALL: "All",
  COVERAGE_MOST: "Most (75%)",
  COVERAGE_HALF: "Half",
  ALIAS_LABEL: "Equal words",
  ALIAS_HINT: "If they write the left word, treat it as the right one (which must be in the expected answer).",
  ALIAS_ACCEPTED_WORD: "They write…",
  ALIAS_ANSWER_WORD: "…counts as",
  ALIAS_NOT_IN_ANSWER: "This word isn't in the expected answer, so this pair will never apply.",
  ADD_ALIAS: "Add equal words",
  MARKS_PATTERN_LABEL: "Marks for a close answer",
  MARKS_ALL_OR_NOTHING: "All or nothing",
  MARKS_HALF: "Half for close",
  MARKS_WEIGHTED: "By similarity",
  MARKS_PATTERN_HINT: "All or nothing is the default: a close-but-wrong answer gets 0.",

  FILL_TITLE_LABEL: "Heading (optional)",
  FILL_TITLE_PLACEHOLDER: "e.g. Complete the sentence",
  FILL_TITLE_HINT: "Shown above the sentence. Leave empty for none.",
  FILL_SENTENCE_LABEL: "Sentence",
  FILL_SENTENCE_PLACEHOLDER: "The capital of Pakistan is [Islamabad].",
  FILL_SENTENCE_HINT: "Put each answer in [square brackets], or select a word and press Make blank.",
  MAKE_BLANK: "Make blank",
  MAKE_BLANK_TITLE: "Turn the selected words into a blank",
  FILL_PREVIEW_LABEL: "How it looks",
  FILL_PREVIEW_EMPTY: "Type the sentence above.",
  FILL_NO_BLANKS_YET: "No blanks yet — wrap an answer in [brackets] to make one.",
  BLANKS_LABEL: "Blanks",
  BLANK_ANSWER: "Answer:",
  BLANK_NO_ANSWER: "(empty)",
  BLANK_ALTERNATIVES_HINT: "Add other answers you'll also accept for each blank.",
  BLANK_ANSWERS_OPTIONAL_MANUAL: "You're marking this quiz yourself, so answers are optional.",
  ADD_ALTERNATIVE_PLACEHOLDER: "Also accept…",
  CHECKING_FLEXIBLE: "Case, punctuation and extra spaces are ignored.",
  CHECKING_STRICT: "Must match exactly — capitals and punctuation count.",
  CHECKING_FLEXIBLE_SHORT: "Flexible",
  CHECKING_STRICT_SHORT: "Strict",

  POLL_TEMPLATES: "Quick fill",
  POLL_SETTINGS: "Poll settings",
  POLL_ALLOW_MULTIPLE: "Let people pick more than one",
  POLL_ANONYMOUS: "Hide who voted for what",
  POLL_ALLOW_CHANGE: "Let people change their vote",
  POLL_ALLOW_OTHER: "Allow an “Other” answer",
  POLL_ASK_REASON: "Ask why they chose it",
  POLL_SHOW_RESULTS: "Show results to voters",
  POLL_SHUFFLE: "Shuffle the choices",
  POLL_NO_TIME_LIMIT: "No time limit for this poll",
  POLL_NOT_SCORED: "Polls aren't scored — they carry no points.",

  POINTS_LABEL: "Points",
  POINTS_RANGE_HINT: "0 to {n}.",
  POINTS_ZERO_HINT: "0 points: counted only as right or wrong.",
  TIME_LABEL: "Time limit",
  TIME_CUSTOM: "Custom time in seconds",
  NO_LIMIT: "No limit",
  NO_LIMIT_HINT: "No countdown for this question.",
  HINT_LABEL: "Hint (optional)",
  HINT_PLACEHOLDER: "A nudge they can ask for",
  REASON_LABEL: "Explanation (optional)",
  REASON_PLACEHOLDER: "Why the answer is right",
  REASON_HINT: "Shown with the result after answering.",

  SECTION_DETAILS: "Quiz details",
  SECTION_SCHEDULE: "Schedule",
  SECTION_MECHANICS: "Quiz Mechanics & Real-Time Feedback",
  SECTION_REVIEW: "Post-Session Review",
  SECTION_EVALUATION: "Evaluation Logic",
  GROUP_LABEL: "Group or class (optional)",
  GROUP_PLACEHOLDER: "e.g. Grade 10-B",
  THEME_LABEL: "Theme colour",
  DEFAULT_TIME_LABEL: "Default time for new questions",
  DEFAULT_TIME_HINT: "Each question can still have its own time.",
  SHARE_CODE_LABEL: "Share code",
  SHARE_CODE_DRAFT_HINT: "Works once the quiz is published.",
  CODE_ON_FIRST_SAVE: "A code is made on the first save.",
  RESET_CODE: "Reset code",
  RESET_CODE_TITLE: "Make a new share code?",
  RESET_CODE_BODY: "The old code stops working for anyone who hasn't joined yet. People who already joined keep their access. Save to apply.",
  CODE_RESET: "New code ready — save to apply it",
  SCHEDULE_START: "Opens",
  SCHEDULE_END: "Closes",
  SCHEDULE_START_NONE: "Opens as soon as it's published.",
  SCHEDULE_END_NONE: "Stays open until you end it.",
  SCHEDULE_END_BEFORE_START: "The closing time must be after the opening time.",
  READING_TIME: "Reading time",

  RULE_NUMBERED: "Numbered Sequence",
  RULE_NUMBERED_SUB: "Display \"Question 1 of 15\" header",
  RULE_TIMER: "Question Timer",
  RULE_TIMER_SUB: "Show gentle elapsed/countdown clock",
  RULE_PREVIEW: "Question preview",
  RULE_PREVIEW_SUB: "Show each question alone before its choices",
  RULE_FLASH: "Instant Correctness Flash",
  RULE_FLASH_SUB: "Green/red glow right after each answer",
  RULE_BACK: "Allow going back",
  RULE_BACK_SUB: "Takers can return to earlier questions",
  RULE_SCORE: "Show Score & Result",
  RULE_SCORE_SUB: "Allow participants to see their score after finishing the quiz",
  RULE_RETAKE: "Retake Allowed",
  RULE_RETAKE_SUB: "Allow multiple attempts to reinforce mastery",
  RULE_MANUAL: "Manual Review & Marking",
  RULE_MANUAL_SUB: "Review open questions personally before scores finalize",
  RULE_PARTIAL: "Partial Credit for Multiple Answers",
  RULE_PARTIAL_SUB: "Award points for each correct option picked instead of all-or-nothing",
  RULE_RAPID: "Rapid Response Bonus",
  RULE_RAPID_SUB: "Award extra points for quick answers",
  PREVIEW_BLOCKED_TIMER_OFF: "Question Preview only plays before a question that has a timer. Turn on Question Timer to use it.",
  PREVIEW_BLOCKED_NO_TIMED: "None of this quiz's questions has a timer, so there's nothing to preview. Give a question a time limit to use it.",
  TIMER_BLOCKED_NO_TIMED: "No question in this quiz has a time limit, so there's nothing to count down. Set a time on a question to use the timer.",
  RAPID_BLOCKED_TIMER_OFF: "The rapid response bonus rewards fast answers to timed questions. Turn on Question Timer to use it.",
  RAPID_BLOCKED_NO_TIMED: "No question in this quiz has a time limit, so there's no speed to reward. Set a time on a question to use the rapid response bonus.",
  RAPID_BLOCKED_MANUAL: "Can't turn this on with Manual Review & Marking — there are no auto-computed points to scale when you're marking every answer by hand.",
  FLASH_BLOCKED_MANUAL: "Can't turn this on with Manual Review & Marking — there's no verdict to reveal until you mark it yourself.",
  PARTIAL_BLOCKED_MANUAL: "Can't turn this on with Manual Review & Marking — there are no auto-computed points to split when you're marking every answer by hand.",
  HEADS_UP: "HEADS UP",
  INSTANT_WARNING_TITLE: "Reveal Answers Right Away?",
  INSTANT_WARNING_BODY: "Students will see the correct answers immediately and could share them with others who are still taking the test.\n\nTurn this on anyway?",
  INSTANT_WARNING_CONFIRM: "Turn On",
  INSTANT_WARNING_CANCEL: "Keep Off",
  BACK_FLASH_WARNING_TITLE: "Takers could fix wrong answers",
  BACK_FLASH_WARNING_BODY: "{flash} shows the right answer after every question. With {back} also on, a taker can see that answer, go back, and change theirs. Turn this on only if that's okay for this quiz.",
  BACK_FLASH_WARNING_CONFIRM: "Turn on anyway",
  BACK_FLASH_WARNING_CANCEL: "Keep it off",

  SAVING: "Saving…",
  SAVED_AGO: "Saved {when}",
  ALL_SAVED: "All changes saved",
  UNSAVED_DRAFT: "Saving soon…",
  UNSAVED_CHANGES: "Unsaved changes",
  UNSAVED: "Unsaved",
  SAVE_CHANGES: "Save changes",
  CHANGES_SAVED: "Changes saved",
  ERR_SAVE_FAILED_SHORT: "Couldn't save",
  ERR_TOO_LONG_TO_SAVE: "Something is over its length limit",
  FIX_BEFORE_PUBLISH: "Fix the highlighted problems, then publish.",
  FIX_BEFORE_SAVE: "Fix the highlighted problems, then save.",
  QUIZ_NOW_LOCKED: "Someone has joined this quiz, so it can't be edited any more.",
  LOCKED_TITLE: "People have already joined or taken this quiz",
  LOCKED_BODY: "Its questions and rules can't change now, so everyone's results stay fair. Duplicate it to make an editable copy.",
  QUESTIONS_NEED_ATTENTION_ONE: "1 question needs attention.",
  QUESTIONS_NEED_ATTENTION: "{n} questions need attention.",
  ERR_SUMMARY_TITLE: "This quiz can't be published yet",

  KEY_SAVE: "Save now",
  KEY_NEW_QUESTION: "New question",
  KEY_DUPLICATE: "Duplicate question",
  KEY_MOVE: "Move question up / down",
  KEY_PREV_NEXT: "Previous / next question",
  KEY_UNDO: "Undo",
  KEY_REDO: "Redo",
  KEY_PICK_TYPE: "Pick a type (empty quiz)",
  KEY_HELP: "Show this list",

  // ── Validation ──
  ERR_TITLE_REQUIRED: "Give your quiz a title.",
  ERR_TITLE_TOO_LONG: "Title is too long (max {n} characters).",
  ERR_NO_QUESTIONS: "Add at least one question.",
  ERR_QUESTION_TEXT_REQUIRED: "This question needs some text.",
  ERR_QUESTION_TEXT_TOO_LONG: "Question is too long (max {n} characters).",
  ERR_OPTION_TOO_LONG: "An option is too long (max {n} characters).",
  ERR_NEED_TWO_OPTIONS: "Fill in at least two options.",
  ERR_DUPLICATE_OPTIONS: "Two options have the same text — make each one different.",
  ERR_NO_CORRECT: "Mark which option is correct.",
  ERR_WRITTEN_ANSWER_REQUIRED: "Enter the answer you expect, or answers will be marked right automatically.",
  ERR_ANSWER_TOO_LONG: "An answer is too long (max {n} characters).",
  ERR_HINT_TOO_LONG: "Hint is too long (max {n} characters).",
  ERR_REASON_TOO_LONG: "Explanation is too long (max {n} characters).",
  ERR_FILL_SENTENCE_REQUIRED: "Write the sentence with its blanks.",
  ERR_NO_BLANKS: "Make at least one blank in the sentence.",
  ERR_BLANK_ANSWER_REQUIRED: "Every blank needs an answer.",
  ERR_TOO_MANY_BLANKS: "A sentence can have at most {n} blanks.",
  ERR_TOO_MANY_BLANK_ANSWERS: "A blank can have at most {n} accepted answers.",
  ERR_TOO_MANY_QUESTIONS: "This quiz is over its limit of {n} questions.",
  ERR_TOO_MANY_OPTIONS: "A question can have at most {n} options.",

  // ── Results ──
  RESULTS: "Results",
  PARTICIPANTS: "Participants",
  EXPORT_CSV: "Export CSV",
  CSV_DOWNLOADED: "CSV downloaded",
  CSV_POLL_ONLY: "Poll-only quizzes have no scores to export.",
  END_QUIZ_NOW: "End quiz now",
  END_QUIZ_TITLE: "End this quiz now?",
  END_QUIZ_BODY: "Nobody new can start it after this. People already taking it can still submit.",
  QUIZ_ENDED: "Quiz ended",
  MARK_N: "Mark {n}",
  STAT_SUBMITTED: "Submitted",
  STAT_AVERAGE: "Average score",
  STAT_AVG_TIME: "Average time",
  STAT_SOURCES: "Web / Android",
  WEB_ANDROID: "where they took it",
  AVERAGE_MARKED_ONLY: "fully marked only",
  N_NOT_STARTED: "+ {n} not started",
  CHART_DISTRIBUTION: "Score distribution",
  CHART_ACCURACY: "Accuracy by question",
  CHART_NO_SCORES: "Scores appear once answers are marked.",
  CHART_BUCKET: "{from}–{to}%: {n}",
  N_WAITING_TO_MARK: "{n} waiting to be marked",
  POLL_RESULTS: "Poll results",
  POLL_NO_VOTES: "No votes yet.",
  POLL_OTHER: "Other",
  NO_ATTEMPTS_TITLE: "No one has taken it yet",
  NO_ATTEMPTS_BODY: "Share the join link — results show up here as people finish.",
  DRAFT_NO_RESULTS_TITLE: "This quiz is still a draft",
  DRAFT_NO_RESULTS_BODY: "Publish it to share the code and start collecting results.",
  SEARCH_PEOPLE: "Search by name",
  FILTER_TO_MARK: "To mark",
  FILTER_GRADED: "Graded",
  FILTER_NOT_STARTED: "Not started",
  NO_PEOPLE_MATCH: "No one matches.",
  N_PEOPLE: "{n} people",
  COL_PERSON: "Person",
  COL_STATUS: "Status",
  COL_SCORE: "Score",
  COL_CORRECT: "Correct",
  COL_TIME: "Time",
  SOURCE_WEB: "Web",
  SOURCE_ANDROID: "Android",
  RETAKEN_N: "Retaken {n}×",
  SUBMITTED_ON: "Submitted {when}",
  RETAKEN_ON: "Retaken {when}",
  MARKS_EDITED_ON: "Marks edited {when}",
  JOINED_ON: "Joined {when}",
  MARK: "Mark",
  REVIEW: "Review",
  REMOVE_PARTICIPANT: "Remove from quiz",
  CONFIRM_REMOVE_TITLE: "Remove this person?",
  CONFIRM_REMOVE_BODY_NAMED: "{name}'s attempt is deleted and they leave the quiz. This can't be undone.",
  PARTICIPANT_REMOVED: "Removed from the quiz",

  // ── Marking ──
  GRADING_TITLE: "Marking",
  // Grading list — the app's own wording (grading_queue_* in res/values/strings.xml).
  GQ_EMPTY_TITLE: "No submissions yet",
  GQ_EMPTY_BODY: "When students submit your quizzes, they show up here for marking and adjusting.",
  GQ_CAUGHT_UP: "All caught up. Nothing is waiting for your mark.",
  GQ_FILTER_PENDING: "Pending",
  GQ_FILTER_AUTO: "Auto-Graded",
  GQ_FILTER_HAND: "Hand-Graded",
  GQ_SECTION_PENDING: "Pending grading",
  GQ_SECTION_COMPLETED: "Completed & graded quizzes",
  GQ_SECTION_AUTO: "Auto-graded quizzes",
  GQ_SECTION_HAND: "Hand-graded quizzes",
  GQ_FILTER_EMPTY: "No quizzes in this filter.",
  GQ_SHOW_ALL: "Show all",
  GQ_AUTO_GRADED: "Auto-graded",
  GQ_HAND_GRADED: "Hand-graded",
  GQ_SUBMISSION_ONE: "1 Submission",
  GQ_SUBMISSIONS: "{n} Submissions",
  GQ_ADJUST_MARKS: "Adjust Marks",
  GQ_VIEW_RESULT: "View Result",
  GQ_GRADE_NOW: "Grade Now",
  GQ_SORT_PENDING: "Pending first",
  GQ_ALL_QUIZZES: "All quizzes",
  GQ_ALL_MARKED: "Everything marked",
  KIND_MCQ: "MCQ",
  KIND_WRITTEN: "Written",
  KIND_POLL: "Poll",
  MARKS_EDITED: "Marks edited",
  MARK_SUBMISSION: "Mark submission",
  ALL_QUIZZES: "All quizzes",
  FILTER_BY_QUIZ: "Filter by quiz",
  N_ANSWERS_WAITING: "{n} answers waiting",
  QUEUE_GROUP_META: "{people} people · {answers} answers to mark",
  MARK_BY_QUESTION: "Mark by question",
  MARK_BY_QUESTION_HINT: "Mark every answer to a question at once — {n} questions have answers waiting",
  SUBMITTED_WHEN: "Submitted {when}",
  MARKING_PROGRESS: "Marking progress",
  MARKED_OF: "{done} of {total} marked",
  ALL_CAUGHT_UP: "All caught up",
  ALL_CAUGHT_UP_BODY: "Nothing is waiting to be marked. New answers show up here as people submit.",
  ALL_CAUGHT_UP_QUIZ: "Nothing in this quiz is waiting to be marked.",
  BACK_TO_QUEUE: "Back to marking",
  BACK_TO_QUIZZES: "Back to my quizzes",
  SUBMISSION_NOT_FOUND: "This submission isn't available",
  SUBMISSION_NOT_FOUND_BODY: "It may have been removed, or the quiz isn't yours.",
  NOTHING_TO_MARK: "Nothing to mark",
  NOTHING_TO_MARK_BODY: "This submission has no scored questions.",
  MARKS: "Marks",
  CORRECT: "Correct",
  TO_MARK: "To mark",
  Q_N_OF: "Question {n} of {total}",
  Q_N: "Q{n}",
  N_MARKS: "{n} marks",
  NO_MARKS: "No marks — right or wrong only",
  NO_MARKS_QUESTION: "This question carries no marks — just choose Correct or Incorrect.",
  FILTER_TYPED: "Typed",
  FILTER_NOT_ADJUSTED: "Not adjusted",
  FILTER_EMPTY: "Nothing here",
  FILTER_EMPTY_BODY: "No question matches this filter.",
  VERDICT_CORRECT: "Correct",
  VERDICT_PARTIAL: "Partial",
  VERDICT_INCORRECT: "Incorrect",
  MARKS_AWARDED: "Marks awarded",
  MARKED: "Marked",
  AUTO_GRADED: "Auto-graded",
  ADJUSTED_BY_YOU: "Adjusted by you",
  CLEAR_MARK: "Clear mark",
  PREVIOUS: "Previous",
  PREVIOUS_QUESTION: "Previous question",
  NEXT_QUESTION: "Next question",
  SAVE_AND_NEXT: "Save & next",
  SAVE_AND_FINISH: "Save & finish",
  SAVE_AND_NEXT_QUESTION: "Save & next question",
  SAVE_MARKS: "Save marks",
  MARKS_SAVED: "Marks saved",
  GRADES_NOT_SAVED_RETAKE: "Not saved — they retook the quiz, so their answers changed. Showing the new ones.",
  NAME_RETOOK: "{name} (retook)",
  SAVE_FAILED_FOR: "Couldn't save for: {names}",
  MARKED_N_ANSWERS: "Marked {n} answers",
  UNDO_PARTLY_FAILED: "Some marks couldn't be undone — check and try again.",
  FEEDBACK_LABEL: "Feedback for this answer (optional)",
  FEEDBACK_PLACEHOLDER: "A short note they'll see with this answer",
  OVERALL_FEEDBACK_LABEL: "Overall feedback",
  OVERALL_FEEDBACK_PLACEHOLDER: "A note on the whole submission",
  OVERALL_FEEDBACK_HINT: "Saved with your next Save & next.",
  QC_WELL_EXPLAINED: "Well explained",
  QC_PARTLY_CORRECT: "Partly correct",
  QC_INCOMPLETE: "Incomplete",
  QC_CHECK_SPELLING: "Check spelling",
  QC_OFF_TOPIC: "Off topic",
  SAVE_QUICK_COMMENT: "Save as chip",
  SAVE_QUICK_COMMENT_HINT: "Save the current note as a quick comment",
  REMOVE_QUICK_COMMENT: "Remove quick comment",
  QUICK_COMMENT_SAVED: "Quick comment saved",
  QUICK_COMMENT_TOO_LONG: "Quick comments can be up to 100 characters.",
  THEIR_ANSWER: "Their answer",
  EXPECTED_ANSWER: "Expected answer",
  ACCEPTED_ANSWERS: "Accepted answers",
  ANSWER_KEY: "Answer key",
  BLANK_N: "Blank {n}",
  NO_ANSWER: "No answer",
  NO_KEY: "No key set",
  SKIPPED_ANSWER: "They skipped this question.",
  SELECTED: "Selected",
  CORRECT_ANSWER: "Correct answer",
  NOT_ATTEMPTED: "Not attempted",
  MIXED_MARKS: "Mixed",
  BY_QUESTION_HINT: "Everyone who gave the same answer is grouped — one mark applies to all of them. Keys: J/K move, C/P/X mark, Enter saves.",
  BQ_CHANGED: "{groups} answers changed · {people} people",
  BQ_NOTHING_CHANGED: "Mark an answer to save it.",
  SUMMARY_DONE: "{name} is fully marked",
  SUMMARY_PARTLY: "Saved for {name}",
  SUMMARY_MARKS: "{got} / {total} marks",
  SUMMARY_CORRECT: "{n} of {total} correct",
  SUMMARY_LEFT: "{n} answers still need a mark.",
  GO_TO_UNMARKED: "Go to first unmarked",
  NEXT_PERSON: "Next person",
  NO_ONE_ELSE: "No one else is waiting in this quiz",

  // ── Errors ──
  ERR_GENERIC: "Something went wrong. Please try again.",
  ERR_LOAD_FAILED: "Couldn't load that. Check your connection and try again.",
  ERR_SAVE_FAILED: "Couldn't save. Check your connection and try again.",
  ERR_NOT_FOUND: "Quiz not found",
  ERR_NOT_FOUND_BODY: "It may have been deleted, or it belongs to another account.",
};

/** Fills {name} placeholders: t(S.QUESTION_N_OF, { n: 3, total: 9 }). */
export function t(template, vars = {}) {
  return String(template).replace(/\{(\w+)\}/g, (whole, key) =>
    Object.prototype.hasOwnProperty.call(vars, key) ? String(vars[key]) : whole
  );
}
