// Every user-facing string for Quizoma Studio (web-v2), in one place.
// Rule names and their warnings use the app's own wording (res/values/strings.xml, cq_*), so a
// setting reads the same on the web and on the phone.

export const S = {
  // ── App-wide ──
  APP_NAME: "Quizoma",
  STUDIO: "Studio",
  BETA: "Beta",
  BETA_NOTE: "Quizzes you make here also appear in your Quizoma app.",
  BETA_SEP: " · ",
  ERR_SIGN_IN_FAILED: "Couldn't sign in. Please try again.",
  SIGN_IN: "Continue with Google",
  SIGN_OUT: "Sign out",
  LOADING: "Loading…",
  CANCEL: "Cancel",
  CLOSE: "Close",
  DELETE: "Delete",
  DUPLICATE: "Duplicate",
  EDIT: "Edit",
  BACK: "Back",
  RETRY: "Try again",
  ADD: "Add",
  CLEAR: "Clear",
  REMOVE: "Remove",
  REMOVE_NAMED: "Remove {name}",
  UNDO: "Undo",
  REDO: "Redo",
  UNDONE: "Undone",
  COPIED: "Copied",
  CODE_COPIED: "Code copied",
  LINK_COPIED: "Join link copied",
  ERR_COPY_FAILED: "Couldn't copy — select it and copy by hand.",
  MORE_ACTIONS: "More actions",
  JUST_NOW: "just now",
  MIN_AGO: "{n} min ago",
  HOURS_AGO: "{n} h ago",
  SECONDS: "seconds",
  SECONDS_SHORT: "{n}s",
  ANONYMOUS: "Anonymous",
  UNTITLED_QUIZ: "Untitled quiz",
  UNTITLED_QUESTION: "Untitled question",
  OWNER: "Owner",
  SHORTCUTS: "Keyboard shortcuts",
  SHOW_ME: "Show me",

  // ── Navigation / shell ──
  NAV_LABEL: "Main",
  NAV_DASHBOARD: "Dashboard",
  NAV_GRADING: "Grading",
  BREADCRUMB: "Breadcrumb",
  NAV_SECTION: "WORKSPACE",
  COLLAPSE_SIDEBAR: "Collapse sidebar",
  EXPAND_SIDEBAR: "Expand sidebar",
  NAV_OPEN_MENU: "Open menu",
  NAV_CLOSE_MENU: "Close menu",
  THEME_CYCLE: "Theme: {theme} — click to change",
  IMPORT_TITLE: "Import from .csv or .txt",
  IMPORT_LABEL: "Import from file",
  QUOTA_LABEL: "Quizzes used",
  QUOTA_USED_OF: "{used} of {limit}",
  QUOTA_USED_POST: " quizzes used",
  QUOTA_HELP: "Drafts and archived count too.",
  QUOTA_EMPTY_PRE: "You can make ",
  QUOTA_EMPTY_N: "{n} quizzes",
  QUOTA_EMPTY_POST: ", up to {q} questions each.",

  // ── Dashboard (design-reference/dashboard.html) ──
  GREETING_LEAD: "{greeting}, ",
  ARROW: "→",
  DOT_SEP: " · ",
  YESTERDAY: "yesterday",
  STATUS_SCHEDULED: "Scheduled",
  CARD_LIVE: "Live",
  MORE_GLYPH: "⋮",
  ACT_GRADE: "Grade",
  ACT_CLOSE_POLL: "Close poll",
  ACT_SHARE: "Share",
  COPY_CODE_LABEL: "Copy share code {code}",
  CONFIRM_CLOSE_POLL_TITLE: "Close this poll?",
  CONFIRM_CLOSE_POLL_BODY: "Nobody can vote once it's closed. The results stay where they are.",
  POLL_CLOSED: "Poll closed",
  QUIZZES_TITLE: "Your quizzes",
  POLL_COUNT_ONE: "1 poll",
  POLL_COUNT_MANY: "{n} polls",
  VOTE_COUNT_ONE: "1 vote",
  VOTE_COUNT_MANY: "{n} votes",
  META_SUBMITTED: "{n} submitted",
  META_CLOSES: "closes {when}",
  META_NO_END: "no end time",
  META_STARTS: "starts {when}",
  META_AVG: "avg {p}%",
  META_CREATED: "created {when}",

  // Next step spotlight — one action, the first rule that applies.
  NEXT_STEP: "NEXT STEP",
  NS_MARK_TITLE_ONE: "1 answer is waiting for your marks",
  NS_MARK_TITLE_MANY: "{n} answers are waiting for your marks",
  NS_MARK_BODY: "{quiz} · {done} of {total} marked",
  NS_MARK_GO: "Start grading",
  NS_MARK_ALL: "See all",
  NS_POLL_TITLE: "Your {quiz} poll is still open",
  NS_POLL_BODY_ONE: "1 vote so far. Close it when you're done.",
  NS_POLL_BODY_MANY: "{n} votes so far. Close it when you're done.",
  NS_POLL_GO: "Review & close",
  NS_SOON_TITLE: "{quiz} starts at {time}",
  NS_SOON_BODY: "Share the code now so participants are ready.",
  NS_SOON_COPY: "Copy code {code}",
  NS_READY_TITLE: "Your {quiz} is ready to share",
  NS_READY_BODY_ONE: "1 question is set. Publish it to get a share code for your participants.",
  NS_READY_BODY_MANY: "{n} questions are set. Publish it to get a share code for your participants.",
  NS_READY_GO: "Publish & get code",
  NS_READY_PREVIEW: "Preview first",
  NS_FINISH_TITLE: "Finish {quiz}",
  NS_FINISH_BODY: "Add {missing} to publish it.",
  NS_MISSING_TITLE: "a title",
  NS_MISSING_QUESTIONS: "questions",
  NS_MISSING_ANSWERS: "the answers",
  CONTINUE_EDITING: "Continue editing",
  NS_LIVE_TITLE_ONE: "1 quiz is live",
  NS_LIVE_TITLE_MANY: "{n} quizzes are live",
  NS_LIVE_BODY_ONE: "1 participant has submitted so far.",
  NS_LIVE_BODY_MANY: "{n} participants have submitted so far.",
  NS_LIVE_GO: "Share a code",
  NS_DONE_TITLE: "All caught up",
  NS_DONE_BODY: "Make your next quiz or reuse one.",
  NS_DONE_DUPLICATE: "Duplicate a quiz",

  // Overview tiles
  TILE_QUIZZES: "Quizzes",
  TILE_MADE: "made",
  LEG_DRAFTS_ONE: "1 draft",
  LEG_DRAFTS_MANY: "{n} drafts",
  LEG_LIVE: "{n} live",
  LEG_SCHEDULED: "{n} scheduled",
  LEG_ENDED: "{n} ended",
  TILE_STUDENTS: "Participants reached",
  STUDENTS_EMPTY: "No participants yet",
  STUDENTS_EMPTY_HINT: "Publish a quiz and share its code. Everyone who joins is counted here.",
  STUDENTS_ACROSS_ONE: "across 1 quiz",
  STUDENTS_ACROSS_MANY: "across {n} quizzes",
  TILE_AVERAGE: "Average score",
  AVERAGE_EMPTY: "No scores yet",
  AVERAGE_EMPTY_HINT: "Once participants submit, you'll see their average here, e.g. 72%.",
  PERCENT: "%",
  AVERAGE_FROM_ONE: "from 1 graded attempt",
  AVERAGE_FROM_MANY: "from {n} graded attempts",

  // Quiz cards
  CHK_QUESTIONS: "✓ Questions",
  CHK_ANSWERS: "✓ Answers set",
  CHK_QUESTION_COUNT_ONE: "✓ 1 question",
  CHK_QUESTION_COUNT_MANY: "✓ {n} questions",
  CHK_TIMER: "Timer {n}s",
  HINT_ADD_TITLE: "Add a title",
  HINT_ADD_QUESTIONS: "Add questions",
  HINT_SET_ANSWERS: "Set answers",
  ADD_QUIZ_SUB: "Write, import a CSV, or use a template",
  QUIZ_LIMIT_FULL: "You've used all {n} quizzes. Archive or delete one to make room.",

  // Footer
  FOOT_COPY: "© {year} Quizoma by CraftByte Studio",
  FOOT_LABEL: "Footer",
  FOOT_PRIVACY: "Privacy Policy",
  FOOT_TERMS: "Terms of Service",
  FOOT_HELP: "Help",
  FOOT_FEEDBACK: "Feedback",

  // ── Dashboard, first run (design-reference/dashboard-welcome.html) ──
  WELCOME_EYEBROW: "WELCOME TO QUIZOMA STUDIO",
  HI_NAMED: "Hi {name}, let's make your ",
  HI_UNNAMED: "Hi, let's make your ",
  HI_MARK: "first quiz.",
  WELCOME_LEAD: "Build it here, share a 6-character code with your participants, and mark answers in minutes. They can join from the app or any browser.",
  CTA_CREATE: "Create a quiz",
  CTA_IMPORT: "Import from CSV",
  FLOW_CREATE: "Create",
  FLOW_SHARE: "Share code",
  FLOW_GRADE: "Grade",
  FLOW_SEP: "›",
  WELCOME_FINE: "Free. No ads. Takes about 2 minutes.",
  DEMO_Q_HEAD: "QUESTION 1 OF 5",
  DEMO_TIMER: "⏱ 30s",
  DEMO_QUESTION: "Which part of a plant makes food?",
  DEMO_OPT_1: "Roots",
  DEMO_OPT_2: "Leaves",
  DEMO_OPT_3: "Stem",
  DEMO_SHARE: "SHARE CODE",
  DEMO_CODE: "K7Q2XA",
  DEMO_JOINED: " participants joined",
  DEMO_JOINED_N: "24",
  DEMO_GRADE: "RAPID GRADE",
  DEMO_GRADE_Q: "Q3",
  DEMO_ANSWER: "photosynthesis",
  DEMO_GROUP: "👥 12",
  DEMO_TICK: "Swipe right · full marks",
  DEMO_TICK_DONE: "12 answers marked in one swipe",
  WAYS_TITLE: "Pick how you want to start",
  WAY_SCRATCH_TITLE: "Write from scratch",
  WAY_SCRATCH_BODY: "Six question types, timers, hints and smart answer checking.",
  WAY_SCRATCH_GO: "Start writing",
  WAY_IMPORT_TITLE: "Import your questions",
  WAY_IMPORT_TAG: "FAST",
  WAY_IMPORT_BODY: "Bring last year's paper from Excel or Google Sheets as .csv or .txt. Check it before saving.",
  WAY_IMPORT_GO: "Choose a file",
  WAY_POLL_TITLE: "Run a quick poll",
  WAY_POLL_BODY: "Ask everyone how a session went. Show results or keep them to yourself.",
  WAY_POLL_GO: "Make a poll",
  TEMPLATES_HINT: "Edit anything before you share",
  ACCOUNT_MENU: "Account",

  // ── Import questions from a file (app: ImportQuestionsScreen, strings.xml imp_*) ──
  IMP_TITLE: "Import Quiz",
  IMP_STEP_1: "STEP 1 OF 2: CHOOSE FILE",
  IMP_CANCEL: "Cancel",
  IMP_BANNER_LEAD: "Saved to private drafts.",
  IMP_BANNER_REST: " You can review and edit questions before sharing.",
  IMP_TITLE_CARD: "Quiz Title",
  IMP_TITLE_PLACEHOLDER: "e.g. Biology Term 1 Test",
  IMP_TITLE_REQUIRED: "Quiz title cannot be empty.",
  IMP_UPLOAD_CARD: "Upload File",
  IMP_SIZE_CHIP: "Up to 2 MB",
  IMP_DROPZONE_TITLE: "Choose .txt or .csv file",
  IMP_DROPZONE_SUB: "Click to browse, or drop a file here",
  IMP_DROP_HERE: "Drop your file here",
  IMP_CHIP_TXT: "📄 .TXT file",
  IMP_CHIP_CSV: "📊 .CSV / Excel",
  IMP_OR: "or",
  IMP_PASTE_LINK: "paste text directly",
  IMP_READING: "Reading file…",
  IMP_CHEAT_TITLE: "💡 Formatting Cheat Sheet",
  IMP_CHEAT_TAG: "Simple & stress-free",
  IMP_CHEAT_TXT_TAB: "Text (.txt)",
  IMP_CHEAT_CSV_TAB: "Spreadsheet (.csv)",
  IMP_CHEAT_TXT_RULE_A: "Separate questions with an empty line. Add an asterisk (",
  IMP_CHEAT_STAR: " * ",
  IMP_CHEAT_TXT_RULE_B: ") next to correct answers.",
  IMP_CHEAT_CSV_RULE: "One row per question: question, options…, correct. The last column is the correct option number (use 1|3 for several).",
  IMP_SAMPLE_HEADER_TXT: "PLAIN TEXT SAMPLE",
  IMP_SAMPLE_HEADER_CSV: "CSV SAMPLE",
  IMP_SAMPLE_COUNT: "{n} QUESTIONS",
  IMP_SAMPLE_COPY: "Copy sample",
  IMP_SAMPLE_COPIED: "Sample copied",
  IMP_FORMAT_TXT_EXAMPLE: "1. What is the capital of Pakistan?\nIslamabad *\nLahore\nKarachi\n\n2. The Earth revolves around the Sun.\nTrue *\nFalse",
  IMP_FORMAT_CSV_EXAMPLE: "question,option1,option2,option3,correct\nWhat is the capital of Pakistan?,Islamabad,Lahore,Karachi,1\nThe Earth revolves around the Sun.,True,False,,1",
  IMP_TEMPLATE_TITLE: "Need a ready-to-use template?",
  IMP_TEMPLATE_SUB: "Download, replace with your questions, then import.",
  IMP_TEMPLATE_TYPES: "INCLUDE QUESTION TYPES:",
  IMP_TYPE_SINGLE: "Single Choice",
  IMP_TYPE_MULTIPLE: "Multiple Choice",
  IMP_TYPE_TF: "True / False",
  IMP_TEMPLATE_DOWNLOAD: "Download Starter Template ({ext})",
  IMP_SAMPLE_SAVED: "Sample file downloaded",
  IMP_SAMPLE_NOTE_1: "Quizoma sample — one question per block, blank line between blocks.",
  IMP_SAMPLE_NOTE_2: "First line = question, each next line = an option. Put * on the correct one(s).",
  IMP_SAMPLE_NOTE_3: "True/False questions just use the two options True and False.",
  IMP_SAMPLE_NOTE_4: "Lines starting with # are ignored. Delete these examples and add your own.",
  IMP_CONTINUE: "Continue to Review",
  IMP_PASTE_TITLE: "Paste your questions",
  IMP_PASTE_HINT: "Same format as the .txt sample — one block per question, * on the correct option.",
  IMP_PASTE_CONFIRM: "Use this text",
  IMP_PASTED_NAME: "Pasted text",
  IMP_FILE_TOO_LARGE: "That file is larger than 2 MB. Question files are plain text — pick a .txt or .csv.",
  IMP_READ_ERROR: "Couldn't read that file. Try a plain .txt or .csv file.",
  IMP_NOTHING_FOUND: "No questions found in this file. Check the cheat sheet below.",
  IMP_SUMMARY: "{ready} ready · {skipped} skipped",
  IMP_CLEAR_FILE: "Remove file",
  IMP_REVIEW_TITLE: "Import from file",
  IMP_REVIEW_STEP: "Step 2 of 2 · Preview & Reorder",
  IMP_REVIEW_INTRO_NEW: "A new quiz is created with your default settings — you can reorganize, fine-tune, or adjust points after importing.",
  IMP_REVIEW_INTRO_EXISTING: "Questions are added to the end of this quiz — you can reorganize, fine-tune, or adjust points after importing.",
  IMP_REVIEW_TITLE_LABEL: "QUIZ TITLE",
  IMP_EDIT_TITLE: "Edit title",
  IMP_REMOVE_FILE: "Remove file",
  IMP_READY_COUNT: "{n} ready",
  IMP_SKIPPED_COUNT: "{n} skipped",
  IMP_REORDER_HINT: "Use ▲▼ to reorder",
  IMP_CORRECT_TAG: "CORRECT",
  IMP_TYPE_SINGLE_CHIP: "One answer",
  IMP_EDIT_SAVE: "Save",
  IMP_EDIT_CANCEL: "Cancel",
  IMP_MOVE_UP: "Move up",
  IMP_MOVE_DOWN: "Move down",
  IMP_EDIT_QUESTION: "Edit question",
  IMP_DELETE_QUESTION: "Remove question",
  IMP_DELETE_BADGE: "REMOVE",
  IMP_DELETE_TITLE: "Remove this question?",
  IMP_DELETE_BODY: "It won't be imported. The file itself isn't changed — you can import it again any time.",
  IMP_DELETE_CONFIRM: "Remove",
  IMP_DELETE_KEEP: "Keep",
  IMP_OPTION_PLACEHOLDER: "Option text",
  IMP_QUESTION_PLACEHOLDER: "Question text",
  IMP_MARK_CORRECT: "Mark as correct",
  IMP_SKIPPED_TITLE: "Skipped",
  IMP_SKIPPED_LINE: "Line {line} — {reason}",
  IMP_LINE_NUMBER: "Line {n}",
  IMP_ISSUE_EMPTY_QUESTION: "question text is empty",
  IMP_ISSUE_TOO_FEW_OPTIONS: "needs at least 2 options",
  IMP_ISSUE_NO_CORRECT: "no correct option marked",
  IMP_ISSUE_DUPLICATE_OPTIONS: "two options have the same text",
  IMP_ISSUE_BAD_CORRECT_REF: "correct column doesn't match any option",
  IMP_ISSUE_OVER_LIMIT: "question or an option is too long, or there are too many options",
  IMP_IMPORT_ONE: "Import 1 question",
  IMP_IMPORT_MANY: "Import {n} questions",
  IMP_IMPORTED_ONE: "1 question imported",
  IMP_IMPORTED_MANY: "{n} questions imported",
  IMP_LIMIT_QUESTIONS_BADGE: "QUESTION LIMIT",
  IMP_LIMIT_QUESTIONS_TITLE: "Question limit reached",
  IMP_LIMIT_QUESTIONS_BODY: "A quiz can have up to {n} questions. Delete a question to add a different one.",
  IMP_LIMIT_QUIZZES_BADGE: "QUIZ LIMIT",
  IMP_LIMIT_QUIZZES_TITLE: "Quiz limit reached",
  IMP_LIMIT_QUIZZES_BODY: "You’ve reached your maximum quiz limit. Delete or archive an older quiz to create room for a new one.",
  IMP_LIMIT_OK: "Got it",
  IMP_QUIZ_LOCKED: "One or more participants have already joined or taken this quiz, so its questions and settings are locked for now. Remove them to edit it again, or duplicate the quiz if you’d rather start a fresh copy.",
  IMP_FROM_FILE: "Import from file",
  IMP_BANK_TITLE: "Import to Question Bank",
  IMP_REVIEW_INTRO_BANK: "Questions are saved to your Question Bank — you can edit points, time and answers there, then add them to any quiz.",
  IMP_LIMIT_BANK_BADGE: "LIMIT",

  // ── Question Bank (app: ui/bank/QuestionBankScreen.kt, strings.xml bank_*) ──
  NAV_BANK: "Question Bank",
  BANK_TITLE: "Question Bank",
  BANK_SUBTITLE: "Save questions once, reuse them in any quiz.",
  BANK_CREATE: "New question",
  BANK_IMPORT: "Import",
  BANK_EXPORT: "Export",
  BANK_HELP: "How this page works",
  BANK_STAT_TOTAL: "{n} of {cap}",
  BANK_STAT_TOTAL_POST: " questions saved",
  BANK_STAT_FULL: "Bank is full",
  BANK_STAT_LEFT: "{n} spaces left",
  BANK_EMPTY_TITLE: "Start Building Your Question Bank",
  BANK_EMPTY_BODY: "Save your questions here once. The fuller your bank gets, the faster new quizzes come together — just pick, mix, and add, no retyping.",
  BANK_CREATE_FIRST: "Create First Question",
  BANK_IMPORT_QUESTIONS: "Import Questions",
  BANK_EMPTY_TIP_1: "Write any of the six question types",
  BANK_EMPTY_TIP_2: "Bring questions in from a file or your quizzes",
  BANK_EMPTY_TIP_3: "Add them to any quiz in two clicks",
  BANK_TYPE_SINGLE_CHOICE: "MCQ",
  BANK_TYPE_MULTIPLE_CORRECT: "Multiple",
  BANK_TYPE_TRUE_FALSE: "True/False",
  BANK_TYPE_WRITTEN: "Written",
  BANK_TYPE_FILL_BLANK: "Fill Blank",
  BANK_TYPE_POLL: "Poll",
  BANK_SEARCH: "Search questions…",
  BANK_FILTER_ALL: "All",
  BANK_FILTER_LABEL: "Filter by type",
  BANK_NO_MATCHES: "No matching questions",
  BANK_NO_MATCHES_BODY: "Try another word, or clear the filter.",
  BANK_CLEAR_FILTERS: "Clear filters",
  BANK_SHOWING: "Showing {n} of {total}",
  BANK_NO_QUESTION_TEXT: "(No question text)",
  BANK_CHIP_SECONDS: "{n} sec",
  BANK_CHIP_PT: "{n} pt",
  BANK_CHIP_PTS: "{n} pts",
  BANK_NOT_SCORED: "Not scored",
  BANK_ANSWER: "Answer: {text}",
  BANK_ANSWER_MORE: "Answer: {text} (+{n} more)",
  BANK_SUMMARY_WRITTEN: "Open-ended evaluation",
  BANK_SUMMARY_FILL: "Fill in the blank",
  BANK_SUMMARY_POLL: "{n} choices · no right answer",
  BANK_SUMMARY_NO_ANSWER: "No correct answer set",
  BANK_WRITTEN_KEY: "Model answer",
  BANK_WRITTEN_NO_KEY: "No model answer — any answer gets full marks unless marked by hand.",
  BANK_BLANK_ANSWER: "Blank {n}: {answers}",
  BANK_EXPAND: "Show answers",
  BANK_COLLAPSE: "Hide answers",
  BANK_ADDED_ON: "Saved {when}",
  BANK_USE_IN_QUIZ: "Use in Quiz",
  BANK_EDIT: "Edit",
  BANK_DELETE: "Delete",
  BANK_SELECT: "Select question",
  BANK_DESELECT: "Deselect question",
  BANK_SELECT_ALL: "Select all",
  BANK_SELECT_ALL_SHOWN: "Select all {n} shown",
  BANK_N_SELECTED: "{n} selected",
  BANK_ADD_TO_QUIZ_N: "Add to Quiz ({n})",
  BANK_LEAVE_SELECTION: "You have questions selected that aren't in a quiz yet.",
  BANK_HELP_BADGE: "QUESTION BANK",
  BANK_HELP_TITLE: "How to reuse questions",
  BANK_HELP_BODY: "• Click a card to see its full answer.\n• Tick the circle to select it — select as many as you like.\n• Click \"Add to Quiz\" to add them all at once, or start a new quiz with them.\n• Import from a .txt / .csv file or from quizzes you've already made.\n• Everything here is the same bank as in your Quizoma app.",
  BANK_HELP_OK: "Got it",
  BANK_DELETE_BADGE: "DELETE",
  BANK_DELETE_TITLE: "Delete this question?",
  BANK_DELETE_BODY: "It will be removed from your Question Bank. Quizzes you already added it to keep their copy.",
  BANK_DELETE_BULK_TITLE_ONE: "Delete 1 question?",
  BANK_DELETE_BULK_TITLE_MANY: "Delete {n} questions?",
  BANK_DELETE_BULK_BODY: "They'll be removed from your Question Bank. Quizzes you already added them to keep their copies.",
  BANK_DELETED_ONE: "Question deleted",
  BANK_DELETED_MANY: "{n} questions deleted",
  BANK_FULL_BADGE: "LIMIT",
  BANK_FULL_TITLE: "Question Bank is full",
  BANK_FULL_BODY: "Your bank holds up to {n} questions. Delete a few to make room for new ones.",
  BANK_FULL_IMPORT_BODY: "Your bank holds up to {n} questions and this would go past it. Delete a few, or import fewer questions.",
  BANK_OK: "Got it",
  // Editor drawer
  BANK_NEW_TITLE: "New bank question",
  BANK_EDIT_TITLE: "Edit bank question",
  BANK_EDITOR_KICKER: "QUESTION BANK",
  BANK_EDITOR_NOTE: "Answers are optional here — a bank question has no quiz yet. Points and time go with it into every quiz you add it to.",
  BANK_SAVE: "Save to bank",
  BANK_SAVE_CHANGES: "Save changes",
  BANK_SAVED: "Saved to Question Bank",
  BANK_UPDATED: "Question updated",
  BANK_DISCARD_TITLE: "Discard this question?",
  BANK_DISCARD_BODY: "What you've typed here hasn't been saved.",
  BANK_DISCARD: "Discard",
  BANK_KEEP_EDITING: "Keep editing",
  BANK_SETTINGS: "Points & time",
  // Import source
  BANK_IMPORT_TITLE: "Import Questions",
  BANK_IMPORT_SUB: "Bring questions in from a file or your own quizzes",
  BANK_IMPORT_FILE_TITLE: "Import from File",
  BANK_IMPORT_FILE_BODY: "Upload a .csv or .txt file, or paste text",
  BANK_IMPORT_QUIZZES_TITLE: "Import from Existing Quizzes",
  BANK_IMPORT_QUIZZES_BODY: "Pick quizzes you've already made and copy their questions in",
  BANK_IMPORT_PICK_TITLE: "Select Quizzes",
  BANK_IMPORT_PICK_SUB: "Their questions will be copied into your bank",
  BANK_IMPORT_PICK_EMPTY: "You don't have any quizzes with questions yet.",
  BANK_QUIZ_COUNT_ONE: "1 question",
  BANK_QUIZ_COUNT_MANY: "{n} questions",
  BANK_IMPORT_CONFIRM_ONE: "Import 1 Question",
  BANK_IMPORT_CONFIRM_MANY: "Import {n} Questions",
  BANK_IMPORT_RESULT_TITLE: "Import complete",
  BANK_IMPORT_RESULT_BADGE: "{n} ADDED",
  BANK_IMPORT_RESULT_ALL: "All questions were added to your bank.",
  BANK_IMPORT_RESULT_SKIPPED_ONE: "1 question was already in your bank, so it was skipped:",
  BANK_IMPORT_RESULT_SKIPPED_MANY: "{n} questions were already in your bank, so they were skipped:",
  BANK_IMPORTED_ONE: "1 question added to your bank",
  BANK_IMPORTED_MANY: "{n} questions added to your bank",
  // Export
  BANK_EXPORT_BADGE: "EXPORT",
  BANK_EXPORT_TITLE: "Export Question Bank",
  BANK_EXPORT_BODY: "Pick a format. Either one can be imported straight back into Quizoma.",
  BANK_EXPORT_TXT: "Text file (.txt)",
  BANK_EXPORT_TXT_SUB: "One block per question — easy to read and edit",
  BANK_EXPORT_CSV: "Spreadsheet (.csv)",
  BANK_EXPORT_CSV_SUB: "One row per question — opens in Excel or Sheets",
  BANK_EXPORT_SAVED: "Question Bank downloaded",
  BANK_EXPORT_NOTHING: "None of your questions can go into a .txt/.csv file — only single, multiple and true/false questions with a correct answer can.",
  BANK_EXPORT_PARTIAL_BADGE: "PARTLY EXPORTED",
  BANK_EXPORT_PARTIAL_TITLE: "Some questions were left out",
  BANK_EXPORT_PARTIAL_ONE: "1 question ({types}) can't be exported to .txt/.csv — that format only holds questions with options and a correct answer. Everything else was saved.",
  BANK_EXPORT_PARTIAL_MANY: "{n} questions ({types}) can't be exported to .txt/.csv — that format only holds questions with options and a correct answer. Everything else was saved.",
  BANK_EXPORT_NOTE_1: "Quizoma Question Bank export.",
  BANK_EXPORT_NOTE_2: "One question per block, blank line between blocks.",
  BANK_EXPORT_NOTE_3: "First line = question, each next line = an option. * marks the correct one(s).",
  BANK_EXPORT_NOTE_4: "This file can be imported straight back into Quizoma.",
  // Add to quiz
  BANK_ADD_TITLE: "Add to Quiz",
  BANK_ADD_SUB: "Select which quiz to insert this question into",
  BANK_ADD_SUB_BULK_ONE: "Select which quiz to insert 1 question into",
  BANK_ADD_SUB_BULK_MANY: "Select which quiz to insert {n} questions into",
  BANK_CREATE_NEW_QUIZ: "Create New Quiz",
  BANK_CREATE_NEW_QUIZ_SUB: "A new draft with these questions — you name it next",
  BANK_QUIZ_SEARCH: "Search your quizzes…",
  BANK_QUIZ_QUESTIONS: "{n}/{cap} questions",
  BANK_NO_QUIZZES: "You haven't created any quizzes yet.",
  BANK_NO_QUIZ_MATCHES: "No quizzes match that search.",
  BANK_NEXT_POSITION: "Next: Choose Position",
  BANK_ADD_N: "Add {n} Questions",
  BANK_ADD_ONE: "Add 1 Question",
  BANK_REASON_ARCHIVED: "Archived — unarchive it first",
  BANK_REASON_LOCKED: "Locked — someone has already joined or attempted it",
  BANK_REASON_FULL: "Full — already at the question limit",
  BANK_LOCKED_BADGE: "LOCKED",
  BANK_LOCKED_TITLE: "Can't add to this quiz",
  BANK_LOCKED_BODY: "This quiz can't take new questions because someone has already joined or attempted it. Remove them first, or pick a different quiz.",
  BANK_LOCKED_MANAGE: "Manage participants",
  BANK_POSITION_TITLE: "Position in Quiz",
  BANK_POSITION_SUB: "Arrange where this question will be placed",
  BANK_CURRENTLY_N: "Currently {n} questions",
  BANK_CURRENTLY_ONE: "Currently 1 question",
  BANK_CURRENTLY_NONE: "No questions yet",
  BANK_CHANGE: "Change",
  BANK_QUICK_PLACEMENT: "Quick placement:",
  BANK_ADD_TO_END: "Add to End (Default)",
  BANK_ADD_AS_FIRST: "Add as First Question",
  BANK_REORDER_HINT: "Drag or use the arrows to reorder:",
  BANK_NEW_BADGE: "✦ New Question (Position #{n} of {total})",
  BANK_Q_SHORT: "Q{n}",
  BANK_ADDING_PROGRESS: "Adding {n} / {total}…",
  BANK_ADDING: "Adding…",
  BANK_CONFIRM_INSERT: "Confirm & Insert Question",
  BANK_ADDED_TO: "Added to {quiz}",
  BANK_ADDED_N_TO: "{n} questions added to {quiz}",
  BANK_OPEN_QUIZ: "Open quiz",
  BANK_INSERT_FAILED_BADGE: "NOT ADDED",
  BANK_INSERT_FAILED_TITLE: "Couldn't add the question",
  BANK_INSERT_FAILED_ARCHIVED: "That quiz has been archived. Unarchive it and try again — nothing was changed.",
  BANK_INSERT_FAILED_LOCKED: "That quiz is locked now that someone has joined or attempted it, so its questions can't change. Nothing was added.",
  BANK_INSERT_FAILED_FULL: "That quiz is already at its question limit. Remove a question from it first — nothing was added.",
  BANK_INSERT_PARTIAL_BADGE: "PARTIALLY ADDED",
  BANK_INSERT_PARTIAL_TITLE: "Added {added} of {total}",
  BANK_INSERT_PARTIAL_BODY: "{added} of {total} selected questions were added to \"{quiz}\". The rest couldn't fit — that quiz is already at its question limit. They're still selected.",
  BANK_TOO_MANY_FOR_QUIZ: "A quiz can have up to {n} questions — select fewer to start a new quiz with them.",
  // Save quiz questions to the bank (dashboard) and pick from the bank (builder)
  BANK_SAVE_QUIZ: "Save questions to bank",
  BANK_SAVING_QUIZ: "Saving to Question Bank…",
  BANK_SAVED_FROM_QUIZ: "Saved {n} questions to Question Bank",
  BANK_SAVED_FROM_QUIZ_ONE: "Saved 1 question to Question Bank",
  BANK_SAVED_FROM_QUIZ_SKIPPED: "Saved {n} questions to Question Bank · {m} already there",
  BANK_QUIZ_HAS_NO_QUESTIONS: "This quiz has no questions to save yet.",
  BANK_VIEW: "View bank",
  BANK_FROM_BANK: "Add from Question Bank",
  BANK_PICK_TITLE: "Add from Question Bank",
  BANK_PICK_SUB: "Pick questions to copy into this quiz. The bank keeps its own copy.",
  BANK_PICK_EMPTY: "Your Question Bank is empty. Save questions there to reuse them in any quiz.",
  BANK_PICK_ROOM: "Room for {n} more in this quiz",
  BANK_PICK_ADD: "Add {n} to quiz",
  BANK_PICK_ADD_ONE: "Add 1 to quiz",
  BANK_PICKED: "{n} questions added from the bank",
  BANK_PICKED_ONE: "1 question added from the bank",
  BANK_OPEN_FULL: "Open Question Bank",

  // ── Sign-in gate ──
  GATE_TITLE: "Welcome to Quizoma Studio",
  GATE_BODY: "Build quizzes, see results and mark answers on a big screen. Sign in with the same Google account you use in the Quizoma app.",
  GATE_NOTE: "Everything here is the same data as your app — quizzes you make here show up on your phone.",

  // ── Dashboard ──
  MY_QUIZZES: "My quizzes",
  NEW_QUIZ: "New quiz",
  GOOD_MORNING: "Good morning",
  GOOD_AFTERNOON: "Good afternoon",
  GOOD_EVENING: "Good evening",
  STAT_TO_MARK: "Waiting to mark",
  FILTER_ALL: "All",
  FILTER_LIVE: "Live",
  FILTER_DRAFTS: "Drafts",
  FILTER_SCHEDULED: "Scheduled",
  FILTER_ENDED: "Ended",
  FILTER_ARCHIVED: "Archived",
  SORT_BY: "Sort by",
  SORT_NEWEST: "Newest first",
  SORT_OLDEST: "Oldest first",
  SORT_SCORE_HIGH: "Highest score",
  SORT_SCORE_LOW: "Lowest score",
  SORT_NAME: "Name A–Z",
  START_FROM_TEMPLATE: "Or start from a template",
  USE_TEMPLATE: "Use template",
  TPL_MATH_TITLE: "Weekly Math Quiz",
  TPL_MATH_BODY: "Times tables, percentages and a quick equation.",
  TPL_MATH_GROUP: "Maths",
  TPL_HISTORY_TITLE: "History Pop Quiz",
  TPL_HISTORY_BODY: "Wars, wonders and civilisations in five minutes.",
  TPL_HISTORY_GROUP: "History",
  TPL_CHECKIN_TITLE: "Quick Check-in",
  TPL_CHECKIN_BODY: "Quick polls on confidence and lesson pace.",
  TPL_CHECKIN_GROUP: "Check-in",
  STATUS_DRAFT: "Draft",
  STATUS_LIVE: "Active",
  STATUS_PUBLISHED: "Published",
  STATUS_ENDED: "Ended",
  STATUS_ARCHIVED: "Archived",
  STATUS_SCHEDULED_AT: "Starts {when}",
  STATUS_READ_ONLY: "Read-only",
  STATUS_GRADED: "Graded",
  QUESTION_COUNT_ONE: "1 question",
  QUESTION_COUNT_MANY: "{n} questions",
  COPY_CODE: "Copy code",
  COPY_LINK: "Copy join link",
  VIEW_RESULTS: "Results",
  PUBLISH: "Publish",
  ARCHIVE: "Archive",
  UNARCHIVE: "Unarchive",
  N_TO_MARK: "{n} to mark",
  COPY_SUFFIX: " (Copy)",
  CONFIRM_DELETE_TITLE: "Delete this quiz?",
  CONFIRM_DELETE_BODY_NAMED: "“{title}”, its questions and every attempt on it will be removed for everyone. This can't be undone.",
  CONFIRM_PUBLISH_TITLE: "Publish this quiz?",
  CONFIRM_PUBLISH_BODY: "People can join with its share code as soon as it's published. A published quiz can't go back to being a draft — you can archive it later instead.",
  PUBLISH_NEEDS_QUESTIONS: "Add at least one question before publishing.",
  PUBLISH_NEEDS_FIXES: "A few things need fixing first — opening the quiz.",
  QUIZ_DELETED: "Quiz deleted",
  QUIZ_DUPLICATED: "Quiz duplicated",
  QUIZ_PUBLISHED: "Quiz published",
  QUIZ_ARCHIVED: "Quiz archived",
  QUIZ_UNARCHIVED: "Quiz restored",
  LIMIT_REACHED_QUIZZES: "You've reached your limit of {n} quizzes. Delete one to make room.",
  CREATE_DISABLED: "Creating quizzes is paused for maintenance right now. Please try again shortly.",

  // ── Builder ──
  NEW_QUIZ_TITLE: "New quiz",
  EDIT_QUIZ_TITLE: "Edit quiz",
  EDIT_QUIZ: "Edit quiz",
  QUIZ_TITLE_LABEL: "Quiz title",
  QUIZ_TITLE_PLACEHOLDER: "Untitled quiz — give it a name",
  QUESTION_EDITOR: "Question editor",
  SETTINGS: "Settings",
  TAB_QUESTION: "Question",
  TAB_QUIZ: "Quiz settings",
  ADD_QUESTION: "Add question",
  OUTLINE_EMPTY: "No questions yet.",
  NO_QUESTIONS_TITLE: "Add your first question",
  NO_QUESTIONS_BODY: "Pick a type to start. You can change it later. Tip: press 1–6.",
  NO_QUESTIONS_LOCKED: "This quiz has no questions.",
  QUESTION_LIMIT_REACHED: "This quiz is at its limit of {n} questions.",
  SELECT_A_QUESTION: "Select a question to see its settings.",
  HAS_PROBLEMS: "Needs attention",
  QUESTION_N_OF: "Question {n} of {total}",
  QUESTION_TYPE: "Question type",
  QUESTION_TEXT_LABEL: "Question",
  QUESTION_TEXT_PLACEHOLDER: "What do you want to ask?",
  DUPLICATE_QUESTION: "Duplicate question",
  DELETE_QUESTION: "Delete question",
  MOVE_UP: "Move up",
  MOVE_DOWN: "Move down",
  QUESTION_DELETED: "Question deleted",
  QUESTION_DUPLICATED: "Question duplicated",
  CHANGE_TYPE_TITLE: "Change the question type?",
  CHANGE_TYPE_BODY: "Switching to {type} drops answers that don't fit it. You can undo with Ctrl+Z.",
  CHANGE_TYPE_CONFIRM: "Change type",
  TYPE_SINGLE: "Single choice",
  TYPE_SINGLE_SUB: "One right answer",
  TYPE_MULTIPLE: "Multiple correct",
  TYPE_MULTIPLE_SUB: "Tick every right answer",
  TYPE_TRUE_FALSE: "True / False",
  TYPE_TRUE_FALSE_SUB: "Quick yes-or-no check",
  TYPE_WRITTEN: "Written answer",
  TYPE_WRITTEN_SUB: "They type the answer",
  TYPE_FILL_BLANK: "Fill in the blanks",
  TYPE_FILL_BLANK_SUB: "Gaps in a sentence",
  TYPE_POLL: "Poll",
  TYPE_POLL_SUB: "Opinions, no right answer",

  OPTIONS_LABEL: "Answer options",
  POLL_CHOICES_LABEL: "Choices",
  ADD_OPTION: "Add option",
  REMOVE_OPTION: "Remove option",
  OPTION_PLACEHOLDER: "Option {n}",
  OPTION_LIMIT_REACHED: "At most {n} options.",
  OPTIONS_PASTED: "Added {n} options from the paste",
  MARK_AS_CORRECT: "Mark as correct",
  MARK_CORRECT_HINT: "Click the circle next to the right answer.",
  MARK_CORRECT_HINT_MULTI: "Tick every right answer.",
  CORRECT_OPTIONAL_MANUAL: "You're marking this quiz yourself, so marking a right answer is optional.",
  ACCEPT_ANY_CORRECT_LABEL: "Any one correct answer is enough",
  ACCEPT_ANY_CORRECT_SUB: "As long as no wrong option is ticked.",
  ACCEPT_ANY_NEEDS_TWO: "Mark at least two right answers to use this.",

  WRITTEN_ANSWER_LABEL: "Expected answer",
  WRITTEN_ANSWER_PLACEHOLDER: "The answer you're looking for",
  WRITTEN_ANSWER_HINT: "Answers are checked against this using the rules below.",
  WRITTEN_ANSWER_HINT_MANUAL: "Optional — you're marking this quiz yourself. It's shown to you as the key while marking.",
  CHECKING_LABEL: "Answer checking",
  MATCH_MODES_LABEL: "How to compare",
  MATCH_MODES_HINT: "Exact and Case-sensitive work alone. Smart match, Keywords and Number can be combined.",
  MODE_SMART: "Smart match",
  MODE_SMART_SUB: "Forgives small typos",
  MODE_EXACT: "Exact",
  MODE_EXACT_SUB: "Same words; case & punctuation ignored",
  MODE_CASE: "Case-sensitive",
  MODE_CASE_SUB: "Capital letters must match",
  MODE_KEYWORDS: "Keywords",
  MODE_KEYWORDS_SUB: "Must mention key words",
  MODE_NUMBER: "Number",
  MODE_NUMBER_SUB: "7 = seven = 7.0",
  STRICTNESS_LABEL: "Strictness",
  STRICTNESS_LENIENT: "More forgiving",
  STRICTNESS_STRICT: "Stricter",
  KEYWORDS_LABEL: "Keywords",
  KEYWORD_PLACEHOLDER: "Type a keyword and press Enter",
  NO_KEYWORDS: "No keywords yet.",
  KEYWORD_COVERAGE: "How many must appear",
  COVERAGE_ALL: "All",
  COVERAGE_MOST: "Most (75%)",
  COVERAGE_HALF: "Half",
  ALIAS_LABEL: "Equal words",
  ALIAS_HINT: "If they write the left word, treat it as the right one (which must be in the expected answer).",
  ALIAS_ACCEPTED_WORD: "They write…",
  ALIAS_ANSWER_WORD: "…counts as",
  ALIAS_NOT_IN_ANSWER: "This word isn't in the expected answer, so this pair will never apply.",
  ADD_ALIAS: "Add equal words",
  MARKS_PATTERN_LABEL: "Marks for a close answer",
  MARKS_ALL_OR_NOTHING: "All or nothing",
  MARKS_HALF: "Half for close",
  MARKS_WEIGHTED: "By similarity",
  MARKS_PATTERN_HINT: "All or nothing is the default: a close-but-wrong answer gets 0.",

  FILL_TITLE_LABEL: "Heading (optional)",
  FILL_TITLE_PLACEHOLDER: "e.g. Complete the sentence",
  FILL_TITLE_HINT: "Shown above the sentence. Leave empty for none.",
  FILL_SENTENCE_LABEL: "Sentence",
  FILL_SENTENCE_PLACEHOLDER: "The capital of Pakistan is [Islamabad].",
  FILL_SENTENCE_HINT: "Put each answer in [square brackets], or select a word and press Make blank.",
  MAKE_BLANK: "Make blank",
  MAKE_BLANK_TITLE: "Turn the selected words into a blank",
  FILL_PREVIEW_LABEL: "How it looks",
  FILL_PREVIEW_EMPTY: "Type the sentence above.",
  FILL_NO_BLANKS_YET: "No blanks yet — wrap an answer in [brackets] to make one.",
  BLANKS_LABEL: "Blanks",
  BLANK_ANSWER: "Answer:",
  BLANK_NO_ANSWER: "(empty)",
  BLANK_ALTERNATIVES_HINT: "Add other answers you'll also accept for each blank.",
  BLANK_ANSWERS_OPTIONAL_MANUAL: "You're marking this quiz yourself, so answers are optional.",
  ADD_ALTERNATIVE_PLACEHOLDER: "Also accept…",
  CHECKING_FLEXIBLE: "Case, punctuation and extra spaces are ignored.",
  CHECKING_STRICT: "Must match exactly — capitals and punctuation count.",
  CHECKING_FLEXIBLE_SHORT: "Flexible",
  CHECKING_STRICT_SHORT: "Strict",

  POLL_TEMPLATES: "Quick fill",
  POLL_SETTINGS: "Poll settings",
  POLL_ALLOW_MULTIPLE: "Let people pick more than one",
  POLL_ANONYMOUS: "Hide who voted for what",
  POLL_ALLOW_CHANGE: "Let people change their vote",
  POLL_ALLOW_OTHER: "Allow an “Other” answer",
  POLL_ASK_REASON: "Ask why they chose it",
  POLL_SHOW_RESULTS: "Show results to voters",
  POLL_SHUFFLE: "Shuffle the choices",
  POLL_NO_TIME_LIMIT: "No time limit for this poll",
  POLL_NOT_SCORED: "Polls aren't scored — they carry no points.",

  POINTS_LABEL: "Points",
  POINTS_RANGE_HINT: "0 to {n}.",
  POINTS_ZERO_HINT: "0 points: counted only as right or wrong.",
  TIME_LABEL: "Time limit",
  TIME_CUSTOM: "Custom time in seconds",
  NO_LIMIT: "No limit",
  NO_LIMIT_HINT: "No countdown for this question.",
  HINT_LABEL: "Hint (optional)",
  HINT_PLACEHOLDER: "A nudge they can ask for",
  REASON_LABEL: "Explanation (optional)",
  REASON_PLACEHOLDER: "Why the answer is right",
  REASON_HINT: "Shown with the result after answering.",

  SECTION_DETAILS: "Quiz details",
  SECTION_SCHEDULE: "Schedule",
  SECTION_MECHANICS: "Quiz Mechanics & Real-Time Feedback",
  SECTION_REVIEW: "Post-Session Review",
  SECTION_EVALUATION: "Evaluation Logic",
  GROUP_LABEL: "Group (optional)",
  GROUP_PLACEHOLDER: "e.g. Grade 10-B",
  THEME_LABEL: "Theme colour",
  DEFAULT_TIME_LABEL: "Default time for new questions",
  DEFAULT_TIME_HINT: "Each question can still have its own time.",
  SHARE_CODE_LABEL: "Share code",
  SHARE_CODE_DRAFT_HINT: "Works once the quiz is published.",
  CODE_ON_FIRST_SAVE: "A code is made on the first save.",
  RESET_CODE: "Reset code",
  RESET_CODE_TITLE: "Make a new share code?",
  RESET_CODE_BODY: "The old code stops working for anyone who hasn't joined yet. People who already joined keep their access. Save to apply.",
  CODE_RESET: "New code ready — save to apply it",
  SCHEDULE_START: "Opens",
  SCHEDULE_END: "Closes",
  SCHEDULE_START_NONE: "Opens as soon as it's published.",
  SCHEDULE_END_NONE: "Stays open until you end it.",
  SCHEDULE_END_BEFORE_START: "The closing time must be after the opening time.",
  READING_TIME: "Reading time",

  RULE_NUMBERED: "Numbered Sequence",
  RULE_NUMBERED_SUB: "Display \"Question 1 of 15\" header",
  RULE_TIMER: "Question Timer",
  RULE_TIMER_SUB: "Show gentle elapsed/countdown clock",
  RULE_PREVIEW: "Question preview",
  RULE_PREVIEW_SUB: "Show each question alone before its choices",
  RULE_FLASH: "Instant Correctness Flash",
  RULE_FLASH_SUB: "Green/red glow right after each answer",
  RULE_BACK: "Allow going back",
  RULE_BACK_SUB: "Takers can return to earlier questions",
  RULE_SCORE: "Show Score & Result",
  RULE_SCORE_SUB: "Allow participants to see their score after finishing the quiz",
  RULE_RETAKE: "Retake Allowed",
  RULE_RETAKE_SUB: "Allow multiple attempts to reinforce mastery",
  RULE_MANUAL: "Manual Review & Marking",
  RULE_MANUAL_SUB: "Review open questions personally before scores finalize",
  RULE_PARTIAL: "Partial Credit for Multiple Answers",
  RULE_PARTIAL_SUB: "Award points for each correct option picked instead of all-or-nothing",
  RULE_RAPID: "Rapid Response Bonus",
  RULE_RAPID_SUB: "Award extra points for quick answers",
  PREVIEW_BLOCKED_TIMER_OFF: "Question Preview only plays before a question that has a timer. Turn on Question Timer to use it.",
  PREVIEW_BLOCKED_NO_TIMED: "None of this quiz's questions has a timer, so there's nothing to preview. Question Preview is only for timed questions. Give a question a time limit to use it.",
  TIMER_BLOCKED_NO_TIMED: "No question in this quiz has a time limit, so there's nothing to count down. Set a time on a question to use the timer.",
  RAPID_BLOCKED_TIMER_OFF: "The rapid response bonus rewards fast answers to timed questions. Turn on Question Timer to use it.",
  RAPID_BLOCKED_NO_TIMED: "No question in this quiz has a time limit, so there's no speed to reward. Set a time on a question to use the rapid response bonus.",
  RAPID_BLOCKED_MANUAL: "Can't turn this on with Mark Answers Myself — there are no auto-computed points to scale when you're marking every answer by hand.",
  FLASH_BLOCKED_MANUAL: "Can't turn this on with Mark Answers Myself — there's no verdict to reveal until you mark it yourself, so nothing could show instantly.",
  PARTIAL_BLOCKED_MANUAL: "Can't turn this on with Mark Answers Myself — there are no auto-computed points to split when you're marking every answer by hand.",
  HEADS_UP: "HEADS UP",
  INSTANT_WARNING_TITLE: "Reveal Answers Right Away?",
  INSTANT_WARNING_BODY: "Participants will see the correct answers immediately and could share them with others who are still taking the test.\n\nTurn this on anyway?",
  INSTANT_WARNING_CONFIRM: "Turn On",
  INSTANT_WARNING_CANCEL: "Keep Off",
  BACK_FLASH_WARNING_TITLE: "Takers could fix wrong answers",
  BACK_FLASH_WARNING_BODY: "{flash} shows the right answer after every question. With {back} also on, a taker can see that answer, go back, and change theirs. Turn this on only if that's okay for this quiz.",
  BACK_FLASH_WARNING_CONFIRM: "Turn on anyway",
  BACK_FLASH_WARNING_CANCEL: "Keep it off",

  SAVING: "Saving…",
  SAVED_AGO: "Saved {when}",
  ALL_SAVED: "All changes saved",
  UNSAVED_DRAFT: "Saving soon…",
  SAVE_CHANGES: "Save changes",
  CHANGES_SAVED: "Changes saved",
  ERR_SAVE_FAILED_SHORT: "Couldn't save",
  ERR_TOO_LONG_TO_SAVE: "Something is over its length limit",
  FIX_BEFORE_PUBLISH: "Fix the highlighted problems, then publish.",
  FIX_BEFORE_SAVE: "Fix the highlighted problems, then save.",
  QUIZ_NOW_LOCKED: "Someone has joined this quiz, so it can't be edited any more.",
  // The checked save was refused: the server copy wins, the page stops saving until reloaded.
  QE_CHANGED_ELSEWHERE: "This quiz was changed in the app or another tab. Reload to see the latest — edits made here since then weren't saved.",
  QE_HAS_ANSWERS: "A question you removed has already been answered, so it can't be deleted. Reload to get it back — edits made here since then weren't saved.",
  QE_RELOAD: "Reload",
  LOCKED_TITLE: "People have already joined or taken this quiz",
  LOCKED_BODY: "Its questions and rules can't change now, so everyone's results stay fair. Duplicate it to make an editable copy.",
  QUESTIONS_NEED_ATTENTION_ONE: "1 question needs attention.",
  QUESTIONS_NEED_ATTENTION: "{n} questions need attention.",
  ERR_SUMMARY_TITLE: "This quiz can't be published yet",

  KEY_SAVE: "Save now",
  KEY_NEW_QUESTION: "New question",
  KEY_DUPLICATE: "Duplicate question",
  KEY_MOVE: "Move question up / down",
  KEY_PREV_NEXT: "Previous / next question",
  KEY_UNDO: "Undo",
  KEY_REDO: "Redo",
  KEY_PICK_TYPE: "Pick a type (empty quiz)",
  KEY_HELP: "Show this list",

  // ── Validation ──
  ERR_TITLE_REQUIRED: "Give your quiz a title.",
  ERR_TITLE_TOO_LONG: "Title is too long (max {n} characters).",
  ERR_NO_QUESTIONS: "Add at least one question.",
  ERR_QUESTION_TEXT_REQUIRED: "This question needs some text.",
  ERR_QUESTION_TEXT_TOO_LONG: "Question is too long (max {n} characters).",
  ERR_OPTION_TOO_LONG: "An option is too long (max {n} characters).",
  ERR_NEED_TWO_OPTIONS: "Fill in at least two options.",
  ERR_DUPLICATE_OPTIONS: "Two options have the same text — make each one different.",
  ERR_NO_CORRECT: "Mark which option is correct.",
  ERR_NEED_TWO_CORRECT: "Mark at least 2 correct answers, or switch to Single choice.",
  ERR_WRITTEN_ANSWER_REQUIRED: "Enter the answer you expect, or answers will be marked right automatically.",
  ERR_ANSWER_TOO_LONG: "An answer is too long (max {n} characters).",
  ERR_HINT_TOO_LONG: "Hint is too long (max {n} characters).",
  ERR_REASON_TOO_LONG: "Explanation is too long (max {n} characters).",
  ERR_FILL_SENTENCE_REQUIRED: "Write the sentence with its blanks.",
  ERR_NO_BLANKS: "Make at least one blank in the sentence.",
  ERR_BLANK_ANSWER_REQUIRED: "Every blank needs an answer.",
  ERR_TOO_MANY_BLANKS: "A sentence can have at most {n} blanks.",
  ERR_TOO_MANY_BLANK_ANSWERS: "A blank can have at most {n} accepted answers.",
  ERR_TOO_MANY_QUESTIONS: "This quiz is over its limit of {n} questions.",
  ERR_TOO_MANY_OPTIONS: "A question can have at most {n} options.",

  // ── Results ──
  RESULTS: "Results",
  PARTICIPANTS: "Participants",
  EXPORT_CSV: "Export CSV",
  CSV_DOWNLOADED: "CSV downloaded",
  CSV_POLL_ONLY: "Poll-only quizzes have no scores to export.",
  END_QUIZ_NOW: "End quiz now",
  END_QUIZ_TITLE: "End this quiz now?",
  END_QUIZ_BODY: "Nobody new can start it after this. People already taking it can still submit.",

  // ── Results release (same words as the app: res/values/strings.xml announce_*, home_results_*,
  //    cq_results_release_*; webtest/text-parity.test.mjs keeps the two in step) ──
  RESULTS_RELEASE_TITLE: "Show results",
  RESULTS_RELEASE_AUTO: "When the quiz ends",
  RESULTS_RELEASE_MANUAL: "When I announce them",
  RESULTS_RELEASE_NO_END: "No end time set. Results appear when you end the quiz.",
  ANNOUNCE_MENU_END_OR_ANNOUNCE: "End quiz / Announce",
  ANNOUNCE_MENU_END_OR_HIDE: "End quiz / Hide results",
  ANNOUNCE_MENU_END_QUIZ: "End quiz",
  ANNOUNCE_MENU_ANNOUNCE: "Announce results",
  ANNOUNCE_MENU_HIDE: "Hide results",
  ANNOUNCE_BADGE: "RESULTS",
  ANNOUNCE_CHOICE_TITLE: "What should happen to the quiz and its results?",
  ANNOUNCE_CHOICE_END_AND_ANNOUNCE: "End quiz and announce",
  ANNOUNCE_CHOICE_END_ONLY: "End quiz only",
  ANNOUNCE_CHOICE_KEEP_OPEN: "Announce now, keep quiz open",
  ANNOUNCE_CHOICE_KEEP_OPEN_HELPER: "Anyone who submits after this sees their result right away and can share answers.",
  ANNOUNCE_CHOICE_HIDE: "Hide results",
  // Announce now, keep quiz open: the cheating warning before anything is written.
  ANNOUNCE_KEEP_OPEN_WARN_TITLE: "The quiz is still open",
  ANNOUNCE_KEEP_OPEN_WARN_BODY: "Anyone who has seen their result can share the answers with people still taking the quiz. To prevent cheating, end the quiz first.",
  ANNOUNCE_HAND_MARKED_NOTE: "Participants with written answers see their result after you mark them.",
  ANNOUNCE_CONFIRM_END_AUTO: "The quiz will close and everyone will see their result.",
  ANNOUNCE_CONFIRM_END_AUTO_MARKED: "The quiz will close and everyone will see their result. Participants with written answers see theirs after you mark them.",
  ANNOUNCE_CONFIRM_TITLE: "Announce results?",
  ANNOUNCE_UNMARKED_ONE: "{n} paper not marked. Announce anyway?",
  ANNOUNCE_UNMARKED_MANY: "{n} papers not marked. Announce anyway?",
  ANNOUNCE_UNKNOWN_UNMARKED_BODY: "Participants with unmarked answers see their result after you mark them.",
  ANNOUNCE_MARK_FIRST: "Mark first",
  ANNOUNCE_ANYWAY: "Announce anyway",
  ANNOUNCE_CONFIRM_ANNOUNCE: "Announce",
  ANNOUNCE_CONFIRM_ALL_BODY: "Participants will see their score and answers for {title}. You can hide them again later, but participants who already looked will have seen them.",
  ANNOUNCE_HIDE_TITLE: "Hide results?",
  ANNOUNCE_HIDE_BODY: "Participants won't see results until you announce again.",
  ANNOUNCE_HIDE_BODY_AUTO: "Participants won't see results until you announce again. This also switches the quiz to \"When I announce them\".",
  ANNOUNCE_HIDE_CONFIRM: "Hide results",
  ANNOUNCE_SNACKBAR_ANNOUNCED: "Results announced",
  ANNOUNCE_SNACKBAR_HIDE: "Hide",
  ANNOUNCE_FAILED: "Couldn't update the results. Try again.",
  // Studio-only: the second step of "End quiz and announce" failed after the quiz had already ended.
  ANNOUNCE_ENDED_NOT_ANNOUNCED: "The quiz ended, but the results were not announced. Announce them from the quiz's menu.",
  ANNOUNCE_CARD_TITLE: "Participant results",
  ANNOUNCE_CARD_AUTO_WITH_END: "Results appear {when}.",
  ANNOUNCE_CARD_AUTO_NO_END: "No end time set. Results appear when you end the quiz.",
  ANNOUNCE_CARD_MANUAL: "Participants can't see results until you announce them.",
  ANNOUNCE_CARD_ANNOUNCED: "Results are out. Participants can see them.",
  ANNOUNCE_CARD_PENDING_ONE: "{n} paper still to mark. Participants with unmarked answers wait for your marks.",
  ANNOUNCE_CARD_PENDING_MANY: "{n} papers still to mark. Participants with unmarked answers wait for your marks.",
  HOME_RESULTS_CHIP_AUTO_WITH_END: "Results at {when}",
  HOME_RESULTS_CHIP_AUTO_NO_END: "Results when you end the quiz",
  HOME_RESULTS_CHIP_NOT_ANNOUNCED: "Not announced",
  HOME_RESULTS_CHIP_ANNOUNCED: "Results announced",
  HOME_RESULTS_ANNOUNCE: "Announce",

  // ── Presets, rule guidance and the setup review (the app's own words: res/values/strings.xml cq_preset_*,
  //    cq_conflict_*, cq_blocked_*, sr_*; webtest/text-parity.test.mjs keeps the two in step) ──
  PRESET_SECTION: "What kind of quiz is this?",
  PRESET_CLASS_TEST: "Test",
  PRESET_CLASS_TEST_TAGLINE: "Answers hidden",
  PRESET_PRACTICE: "Practice",
  PRESET_PRACTICE_TAGLINE: "Learn and retry",
  PRESET_SPEED_DRILL: "Speed drill",
  PRESET_SPEED_DRILL_TAGLINE: "Fast and fun",
  PRESET_SUMMARY_CLASS_TEST: "Participants only see that their paper was submitted. Their score and answers appear when the quiz ends (or when you announce them).",
  PRESET_SUMMARY_PRACTICE: "Participants see their score, the right answers and your explanations right after submitting.",
  PRESET_SUMMARY_SPEED_DRILL: "Each answer flashes right or wrong instantly. Faster answers earn more points.",
  PRESET_SUMMARY_CUSTOM: "Your own settings",
  PRESET_SUMMARY_PRACTICE_MANUAL: "Participants see their score, the right answers and your explanations after you mark their answers.",
  PRESET_SUMMARY_SPEED_DRILL_MANUAL: "A timed drill with retakes. Scores appear after you mark them.",
  PRESET_SUMMARY_ONLY_POLLS: "This quiz has only polls, so participants just see that their answers were sent.",
  PRESET_CHIP_INSTANT: "Instant",
  PRESET_CHIP_SHOWN: "Shown",
  PRESET_CHIP_HIDDEN: "Hidden",
  PRESET_CHIP_TIMED: "Timed",
  PRESET_CHIP_NO_TIMER: "No timer",
  PRESET_CHIP_RETAKES: "Retakes",
  PRESET_CHIP_ONE_TRY: "One try",
  CONFLICT_RETAKE_WITH_ANSWERS: "Participants can see the answers, then retake. The new attempt replaces their earlier score.",
  CONFLICT_BACK_ON_TIMED: "Going back restarts a question's timer, so participants get extra time.",
  CONFLICT_MANUAL_OFF_OPEN_ANSWERS: "Written and fill-in answers will be marked automatically.",
  CONFLICT_MARK_MYSELF: "Mark them myself",
  BLOCKED_ONLY_POLLS: "This quiz has only polls, so there's nothing to score.",
  PARTIAL_BLOCKED_NO_MULTIPLE: "No question in this quiz allows several answers.",
  SR_TITLE: "Before your quiz goes out",
  SR_MESSAGE: "Here's how your settings will work with the questions you wrote.",
  SR_TITLE_MUST: "One thing to sort out first",
  SR_MESSAGE_MUST: "Some questions can't be checked automatically yet. Choose how you want to handle them.",
  SR_MISSING_ANSWERS_ONE: "{n} question doesn't have a correct answer, so it can't be checked automatically.",
  SR_MISSING_ANSWERS_MANY: "{n} questions don't have a correct answer, so they can't be checked automatically.",
  SR_NO_QUESTIONS: "This quiz has no questions yet, so there's nothing for anyone to take.",
  SR_ACTION_ADD_QUESTION: "Add a question",
  SR_ACTION_MARK_MYSELF: "Mark answers myself instead",
  SR_ACTION_EDIT_ONE: "Pick its correct answer",
  SR_ACTION_EDIT_MANY: "Pick their correct answers",
  SR_MANUAL: "You'll mark every answer yourself. Any correct answers and points you set are kept, so you can switch back to automatic checking anytime.",
  SR_RESULT_NO_ANSWER_ONE: "Participants will see their result, but {n} question has no correct answer to show them.",
  SR_RESULT_NO_ANSWER_MANY: "Participants will see their result, but {n} questions have no correct answer to show them.",
  SR_TIMERS_OFF_ONE: "Timers are off, so the time limit on {n} question won't be used. It stays saved if you turn timers back on.",
  SR_TIMERS_OFF_MANY: "Timers are off, so the time limits on {n} questions won't be used. They stay saved if you turn timers back on.",
  SR_ACTION_TIMERS_ON: "Turn timers on",
  SR_RAPID_NO_EFFECT: "Rapid scoring only rewards fast answers on timed questions — none of yours are timed, so it won't change any scores.",
  SR_ACTION_RAPID_OFF: "Turn rapid scoring off",
  SR_SAVE_SETTINGS: "Save Settings",
  SR_GO_BACK: "Go back",
  QUIZ_ENDED: "Quiz ended",
  MARK_N: "Mark {n}",
  STAT_SUBMITTED: "Submitted",
  STAT_AVERAGE: "Average score",
  STAT_AVG_TIME: "Average time",
  STAT_SOURCES: "Web / Android",
  WEB_ANDROID: "where they took it",
  AVERAGE_MARKED_ONLY: "fully marked only",
  N_NOT_STARTED: "+ {n} not started",
  CHART_DISTRIBUTION: "Score distribution",
  CHART_ACCURACY: "Accuracy by question",
  CHART_NO_SCORES: "Scores appear once answers are marked.",
  CHART_BUCKET: "{from}–{to}%: {n}",
  N_WAITING_TO_MARK: "{n} waiting to be marked",
  POLL_RESULTS: "Poll results",
  POLL_NO_VOTES: "No votes yet.",
  POLL_OTHER: "Other",
  NO_ATTEMPTS_TITLE: "No one has taken it yet",
  NO_ATTEMPTS_BODY: "Share the join link — results show up here as people finish.",
  DRAFT_NO_RESULTS_TITLE: "This quiz is still a draft",
  DRAFT_NO_RESULTS_BODY: "Publish it to share the code and start collecting results.",
  SEARCH_PEOPLE: "Search by name",
  FILTER_TO_MARK: "To mark",
  FILTER_GRADED: "Graded",
  FILTER_NOT_STARTED: "Not started",
  NO_PEOPLE_MATCH: "No one matches.",
  N_PEOPLE: "{n} people",
  COL_PERSON: "Person",
  COL_STATUS: "Status",
  COL_SCORE: "Score",
  COL_CORRECT: "Correct",
  COL_TIME: "Time",
  SOURCE_WEB: "Web",
  SOURCE_ANDROID: "Android",
  RETAKEN_N: "Retaken {n}×",
  SUBMITTED_ON: "Submitted {when}",
  RETAKEN_ON: "Retaken {when}",
  MARKS_EDITED_ON: "Marks edited {when}",
  JOINED_ON: "Joined {when}",
  MARK: "Mark",
  REVIEW: "Review",
  REMOVE_PARTICIPANT: "Remove from quiz",
  CONFIRM_REMOVE_TITLE: "Remove this person?",
  CONFIRM_REMOVE_BODY_NAMED: "{name}'s attempt is deleted and they leave the quiz. This can't be undone.",
  PARTICIPANT_REMOVED: "Removed from the quiz",

  // ── Grading (marking) ──
  GRADING_TITLE: "Grading",
  // Grading list — the app's own wording (grading_queue_* in res/values/strings.xml).
  ALL_QUIZZES: "All quizzes",
  FILTER_BY_QUIZ: "Filter by quiz",
  QUEUE_GROUP_META: "{people} people · {answers} answers to mark",
  MARK_BY_QUESTION_HINT: "Mark every answer to a question at once — {n} questions have answers waiting",
  ALL_CAUGHT_UP_BODY: "Nothing is waiting to be marked. New answers show up here as people submit.",
  BACK_TO_QUIZZES: "Back to my quizzes",

  // ── Quiz editor (design-reference/editor.html) ──
  // Setting titles are the app's (strings.xml); the line under each is the reference's wording.
  QE_BETA: "Beta",
  QE_HELP: "HELP",
  QE_USER_GUIDE: "User guide",
  QE_FAQS: "FAQs",
  QE_SUPPORT: "Support",
  QE_FEEDBACK: "Send feedback",
  QE_THEME: "Theme",
  QE_THEME_LIGHT: "Light",
  QE_THEME_DARK: "Dark",
  QE_THEME_SYSTEM: "System",
  QE_DELETE_ACCOUNT: "Delete account",
  QE_DASHBOARD: "Dashboard",
  QE_UNTITLED: "Untitled quiz",
  QE_DRAFT: "Draft",
  QE_PUBLISHED: "Published",
  QE_READ_ONLY: "Read-only",
  QE_SAVED: "All changes saved",
  QE_SAVING: "Saving…",
  QE_UNSAVED: "Unsaved changes",
  QE_SAVE_FAILED: "Couldn't save",
  QE_SAVED_TIP: "Saved {when} · also in your Quizoma app",
  QE_JUST_NOW: "just now",
  QE_SEC_AGO: "{n} sec ago",
  QE_MIN_AGO: "{n} min ago",
  QE_HISTORY: "History",
  QE_UNDO_TITLE: "Undo (Ctrl+Z)",
  QE_REDO_TITLE: "Redo (Ctrl+Shift+Z)",
  QE_UNDONE: "Undone",
  QE_REDONE: "Redone",
  QE_SHORTCUTS: "Keyboard shortcuts",
  QE_SHORTCUTS_TITLE: "Keyboard shortcuts (?)",
  QE_IMPORT: "Import",
  QE_PUBLISH: "Publish",
  QE_SAVE: "Save changes",
  QE_ALMOST: "Almost there",
  QE_CHECK_WRITE: "Write every question",
  QE_CHECK_FINISH: "Finish every question",
  QE_CHECK_NAME: "Give the quiz a name",
  QE_SAFE: "Nobody sees it until you share the code.",
  QE_SAFE_TIP_A: " Tip: check ",
  QE_SAFE_TIP_U: "Preview",
  QE_SAFE_TIP_B: " first.",
  QE_PREVIEW: "Preview",
  QE_PREV_LOCK_T: "Nothing to preview yet",
  QE_PREV_LOCK_B: "Finish at least one question first — then you can see it exactly like participants do.",
  QE_PV_LABEL: "Quiz preview",
  QE_PV_NOTE: "Preview · only you see this, nothing is saved",
  QE_PV_CLOSE: "Close preview",
  QE_TITLE_PH: "Name your quiz — or do it at the end",
  QE_TITLE_PH_SHORT: "Name your quiz",
  QE_IDEAS: "Ideas:",
  QE_IDEA_TEST: "Test · {date}",
  QE_IDEA_WEEKLY: "Weekly quiz",
  QE_IDEA_QUICK: "Quick check",
  QE_IDEA_REVISION: "Revision quiz",
  QE_Q_ONE: "1 question",
  QE_Q_MANY: "{n} questions",
  QE_TAKE_SEC: "about {n} sec to take",
  QE_TAKE_MIN: "about {n} min to take",
  QE_ALWAYS_OPEN: "Always open",
  QE_STARTS_NO_END: "Starts {when}, {time} · no end time",
  QE_STARTS_NO_END_SET: "Starts {when}, {time} · end time not set",
  QE_END_ONLY: "Closes {when}, {time}",
  QE_TODAY: "Today",
  QE_TOMORROW: "Tomorrow",
  QE_QUESTIONS: "Questions",
  QE_COUNT_OF: "{n} / {max}",
  QE_NEW_QUESTION: "New question",
  QE_NOT_STARTED: "Not started yet",
  QE_STEPS_DONE: "{n} of {total} done",
  QE_DRAG_HINT: "Drag to reorder · Alt+↑/↓",
  QE_ADD_QUESTION: "Add question",
  QE_FROM_BANK: "From Question Bank",
  QE_PROGRESS: "Quiz progress",
  QE_ALL_DONE: "All questions complete ✓",
  QE_FINISH_FIRST: "Finish your first question",
  QE_FINISH_N: "Finish your {n} questions",
  QE_N_COMPLETE_ONE: "{done} complete · 1 still needs work",
  QE_N_COMPLETE_MANY: "{done} complete · {left} still need work",
  QE_CAN_PUBLISH: "You can publish now",
  QE_STAT_QUESTIONS: "questions",
  QE_STAT_TIME: "to take",
  QE_STAT_POINTS: "points",
  QE_SEC_SHORT: "{n}s",
  QE_MIN_SHORT: "{n} min",
  QE_KEY_NEW_OPTION: "New option",
  QE_KEY_NEXT: "Next question",
  QE_KEY_TYPE: "Change type",
  QE_ALL_SHORTCUTS: "All shortcuts",
  QE_QUESTION_N_OF: "QUESTION {n} OF {total}",
  QE_DUPLICATE: "Duplicate",
  QE_DUPLICATE_Q: "Duplicate question",
  QE_DELETE: "Delete",
  QE_DELETE_Q: "Delete question",
  QE_TYPE_MENU: "Question type",
  QE_TYPE_GROUP: "QUESTION TYPE",
  QE_TEXT_PH: "Type your question here…",
  QE_FB_TITLE_PH: "Optional heading shown above the sentence…",
  QE_ANSWERS: "ANSWERS",
  QE_OPTIONS: "OPTIONS",
  QE_HINT_SINGLE: "Tap the circle for the right answer",
  QE_HINT_MULTI: "Tick every right answer",
  QE_HINT_POLL: "No right answer",
  QE_HINT_MANUAL: "Optional — you mark it yourself",
  QE_OPTION_N: "Option {n}",
  QE_MARK_N: "Mark option {n} as correct",
  QE_CORRECT: "Correct",
  QE_REMOVE_OPTION: "Remove option",
  QE_ADD_OPTION: "+ Add option",
  QE_MIN_OPTIONS: "A question needs at least 2 options",
  QE_MAX_OPTIONS: "{n} options is the most for one question",
  QE_QUICK_FILL: "Quick fill",
  QE_FILL_YES_NO: "Yes / No",
  QE_FILL_YES_NO_MAYBE: "Yes / No / Maybe",
  QE_FILL_AGREE: "Agree / Neutral / Disagree",
  QE_FILL_LIKERT: "Likert scale",
  QE_FILL_DAYS: "Days of the week",
  QE_FILL_1_5: "Rating 1–5",
  QE_FILL_1_10: "Rating 1–10",
  QE_EXPECTED: "EXPECTED ANSWER",
  QE_EXPECTED_SUB: "Used to mark automatically",
  QE_EXPECTED_PH: "e.g. photosynthesis",
  QE_EXPECTED_HINT: "Small typos like “fotosynthesis” still count. Change how it's checked in the settings below.",
  QE_EXPECTED_HINT_PLAIN: "Change how it's checked in the settings below.",
  QE_EXPECTED_HINT_MANUAL: "You're marking this quiz yourself, so this is optional. It's shown to you as the key while marking.",
  QE_SENTENCE: "YOUR SENTENCE",
  QE_SENTENCE_SUB: "Select a word to make it a blank",
  QE_SENTENCE_PH: "Plants make food in their [leaves] using sunlight.",
  QE_MAKE_BLANK: "Make blank",
  QE_SENTENCE_HINT: "Or put each answer in [square brackets].",
  QE_PREVIEW_EMPTY: "Your sentence shows here, with each blank drawn as a gap.",
  QE_BLANK_N: "Blank {n}",
  QE_BLANK_EMPTY: "(no answer yet)",
  QE_BLANK_ANSWERS: "{n} / {max} answers",
  QE_ALSO_ACCEPT_PH: "Also accept… (Enter)",
  QE_BLANK_POINTS: "Points for blank {n}",
  QE_REMOVE_ALT: "Remove {name}",
  QE_STEP_WRITE: "Write the question",
  QE_STEP_OPTIONS: "Add 2+ options",
  QE_STEP_MARK: "Mark the right answer",
  QE_STEP_MARK_MULTI: "Mark the right answers",
  QE_STEP_TF: "Pick True or False",
  QE_STEP_EXPECTED: "Add the expected answer",
  QE_STEP_SENTENCE: "Write the sentence",
  QE_STEP_BLANK: "Make 1+ blank",
  QE_STEP_BLANK_ANSWERS: "Give every blank an answer",
  QE_TO_FINISH: "To finish this question:",
  QE_COMPLETE: "Question complete",
  QE_NEXT: "Next question",
  QE_GO_TO: "Go to question {n}",
  QE_KBD_NEXT: "Ctrl ↵",
  QE_MISS_WRITE: "Write the question",
  QE_MISS_OPTIONS: "Add at least 2 options",
  QE_MISS_MARK: "Tap the circle next to the right answer",
  QE_MISS_MARK_MULTI: "Tick at least 1 right answer",
  QE_MISS_DUPLICATE: "Two options are the same",
  QE_MISS_EXPECTED: "Add the expected answer",
  QE_MISS_SENTENCE: "Write the sentence",
  QE_MISS_BLANK: "Make at least 1 blank",
  QE_MISS_BLANK_ANSWER: "Give every blank an answer",
  QE_Q_SETTINGS: "Question settings",
  QE_ONLY_FOR: "Only for question {n}",
  QE_TIME: "TIME LIMIT",
  QE_CUSTOM: "Custom",
  QE_NO_LIMIT: "No limit",
  QE_YOUR_TIME: "Your time",
  QE_MINUTES: "Minutes",
  QE_SECONDS: "Seconds",
  QE_MIN: "min",
  QE_SEC: "sec",
  QE_TIME_NOTE: "Up to 60 minutes.",
  QE_TIME_MAX: "60 minutes is the most for one question.",
  QE_TIME_MIN: "At least 5 seconds.",
  QE_POINTS: "POINTS",
  QE_POINTS_SUB: "0 to {max} · 0 = just right or wrong",
  QE_POINTS_SUB_FB: "1 to {max} · shared across the blanks",
  QE_POINTS_LABEL: "Points (0 to {max})",
  QE_FEWER: "Fewer points",
  QE_MORE_PTS: "More points",
  QE_POINTS_MAX: "{max} points is the most for one question.",
  QE_POLL_NO_POINTS: "Polls carry no points and never change a score.",
  QE_SAME_FOR_ALL: "Same for every question?",
  QE_APPLY_ALL: "Use {what} for all {n} questions",
  QE_APPLY_TIME_PTS: "{time} · {pts} pts",
  QE_NO_TIME_LIMIT: "no time limit",
  QE_APPLIED: "Applied to all questions",
  QE_HINT: "HINT",
  QE_HINT_SUB: "optional",
  QE_HINT_PH: "A small nudge participants can reveal",
  QE_REASON: "REASON",
  QE_REASON_SUB: "optional · shown after they finish",
  QE_REASON_PH: "Why is this the right answer?",
  QE_MULTI_TITLE: "Multiple correct",
  QE_MUST_PICK: "TO BE CORRECT, PARTICIPANT MUST PICK",
  QE_PICK_ALL_N: "All {n}",
  QE_PICK_BOTH: "Both",
  QE_PICK_ANY: "Any one",
  QE_PICK_EITHER: "Either one",
  QE_PICK_ALL_NOTE: "Every correct option, and no wrong ones.",
  QE_PICK_ANY_NOTE: "At least one correct option, and no wrong ones.",
  QE_PARTIAL_NOTE: "Partial credit is turned on for the whole quiz in Quiz settings.",
  QE_CHECKING: "Answer Checking",
  QE_HOW_MATCH: "HOW TO MATCH",
  QE_HOW_MATCH_SUB: "Exact works alone · the rest can combine",
  QE_MODE_EXACT: "Exact",
  QE_MODE_CASE: "Case sensitive",
  QE_MODE_KEYWORDS: "Keywords",
  QE_MODE_NUMBER: "Number",
  QE_KEYWORDS: "KEYWORDS",
  QE_KEYWORDS_SUB: "must appear in the answer",
  QE_KEYWORD_PH: "Type a keyword and press Enter",
  QE_KEYWORDS_NEEDED: "KEYWORDS NEEDED",
  QE_COVER_ALL: "All",
  QE_COVER_MOST: "Most (75%)",
  QE_COVER_HALF: "At least half",
  QE_EQUAL_WORDS: "EQUAL WORDS",
  QE_EQUAL_WORDS_SUB: "optional · other words that mean the same",
  QE_ALIAS_ANSWER: "Word from your answer",
  QE_ALIAS_ACCEPT: "Equal word to accept",
  QE_ALIAS_REMOVE: "Remove this pair",
  QE_ALIAS_NOT_IN: "This word isn't in the expected answer, so this pair will never apply.",
  QE_ADD_ANOTHER: "+ Add another",
  QE_MARKS: "HOW ARE MARKS GIVEN?",
  QE_MARKS_SUB: "for close answers",
  QE_MARKS_ALL: "All or nothing",
  QE_MARKS_HALF: "Half for close",
  QE_MARKS_SIM: "By similarity",
  QE_STRICTNESS: "TYPO STRICTNESS",
  QE_STRICTNESS_SUB: "how close a typo can be",
  QE_FORGIVING: "Forgiving",
  QE_STRICT: "Strict",
  QE_SHORT_EXACT: "Answers of 3 letters or fewer are always checked exactly.",
  QE_TRY: "TRY IT OUT",
  QE_TRY_PH: "Type a participant answer to test",
  QE_TRY_IDLE: "Type above to see how it would be marked.",
  QE_TRY_NEED: "Add the expected answer first.",
  QE_TRY_OK: "✓ Correct · {n}% similar",
  QE_TRY_PARTIAL: "◐ Close · {n}% similar",
  QE_TRY_NO: "✗ Not accepted · {n}% similar",
  QE_TRY_UNAVAILABLE: "Testing isn't available right now.",
  QE_FB_TITLE: "Blanks",
  QE_FB_POINTS: "POINTS PER BLANK",
  QE_FB_POINTS_OFF: "Off",
  QE_FB_POINTS_SPLIT: "Split equally",
  QE_FB_POINTS_EACH: "Set per blank",
  QE_FB_POINTS_NOTE_OFF: "One total for the question.",
  QE_FB_POINTS_NOTE_SPLIT: "The question's points are shared equally across the blanks.",
  QE_FB_POINTS_NOTE_EACH: "Set each blank's own points in the sentence above. Total: {n} points.",
  QE_FB_CHECKING: "ANSWER CHECKING",
  QE_FB_FLEXIBLE: "Flexible",
  QE_FB_STRICT: "Strict",
  QE_FB_FLEXIBLE_NOTE: "Flexible ignores capitals, punctuation and extra spaces.",
  QE_FB_STRICT_NOTE: "Strict is an exact match — capitals and punctuation both count.",
  QE_FB_LIMITS: "Up to {blanks} blanks, and up to {answers} accepted answers for each blank.",
  QE_POLL_TITLE: "Poll settings",
  QE_POLL_MULTI: "Allow multiple answers",
  QE_POLL_MULTI_SUB: "Voters can pick more than one",
  QE_POLL_ANON: "Anonymous voting",
  QE_POLL_ANON_SUB: "Results show totals only",
  QE_POLL_REASON: "Ask for a reason",
  QE_POLL_REASON_SUB: "Voters can add a short why",
  QE_POLL_CHANGE: "Allow vote change",
  QE_POLL_CHANGE_SUB: "Until you close the poll",
  QE_POLL_OTHER: "Other (own answer)",
  QE_POLL_OTHER_SUB: "Voters type their own answer",
  QE_POLL_SHUFFLE: "Shuffle options",
  QE_POLL_SHUFFLE_SUB: "Different order for each voter",
  QE_POLL_RESULTS: "Show results to voters",
  QE_POLL_RESULTS_SUB: "After they vote",
  QE_POLL_ANON_NOTE: "Hiding votes keeps names out of results, but don't use polls for anything sensitive.",
  QE_RAPID: "RAPID RESPONSE BONUS",
  QE_RAPID_SUB: "this question only",
  QE_RAPID_DEFAULT_ON: "Quiz default (on)",
  QE_RAPID_DEFAULT_OFF: "Quiz default (off)",
  QE_RAPID_ON: "On",
  QE_RAPID_OFF: "Off",
  QE_RAPID_MANUAL: "Not available with Manual Review & Marking.",
  QE_QUIZ_SETTINGS: "Quiz settings",
  QE_FOR_WHOLE: "For the whole quiz",
  QE_HIDE_SETTINGS: "Hide quiz settings",
  QE_HIDE_SETTINGS_TITLE: "Hide settings",
  QE_SHOW_SETTINGS: "Show quiz settings",
  QE_SETTINGS_HIDDEN: "Settings hidden · more room to write",
  QE_START_END: "START & END TIME",
  QE_WHEN_ANY: "Always open",
  QE_WHEN_ANY_SUB: "Participants can start anytime, until you end it",
  QE_WHEN_SET: "Set start & end time",
  QE_WHEN_SET_SUB: "Opens and closes automatically on a clock",
  QE_START_LABEL: "START · quiz opens at",
  QE_END_LABEL: "END · quiz closes after",
  QE_START_DATE: "Start date",
  QE_START_TIME: "Start time",
  QE_END_DATE: "End date",
  QE_END_TIME: "End time",
  QE_DUR_15: "15 min",
  QE_DUR_30: "30 min",
  QE_DUR_60: "1 hour",
  QE_DUR_DAY: "1 day",
  QE_DUR_NONE: "No end",
  QE_DUR_CUSTOM: "Custom",
  QE_END_AFTER: "End time must be after the start time.",
  QE_OPEN_FOR_MIN: "Open for {n} minutes",
  QE_OPEN_FOR_HOUR: "Open for 1 hour",
  QE_OPEN_FOR_HOURS: "Open for {n} h",
  QE_OPEN_FOR_HM: "Open for {h} h {m} min",
  QE_OPEN_FOR_DAY: "Open for 1 day",
  QE_OPEN_FOR_DAYS: "Open for {n} days",
  QE_STAYS_OPEN: "Stays open until you end it",
  QE_ONWARDS: "{when}, {time} onwards",
  QE_RANGE: "{when}, {start} – {end}",
  QE_SEC_RESULTS: "RESULTS",
  QE_SEC_MARKING: "MARKING",
  QE_SEC_WHILE_TAKING: "WHILE TAKING THE QUIZ",
  QE_SEC_LOOK: "LOOK",
  QE_PALETTE: "SUBJECT ACCENT PALETTE",
  QE_R_NUMBERED_SUB: "Show “Question 1 of 15” at the top",
  QE_R_TIMER_SUB: "Count down on each question",
  QE_R_PREVIEW_SUB: "Show the question {n}s before the options",
  QE_R_PREVIEW_OFF_SUB: "Show the question before the options",
  QE_R_FLASH_SUB: "Show right / wrong after each answer",
  QE_R_BACK_SUB: "Participants can change earlier answers",
  QE_R_SCORE_SUB: "Off keeps answers private",
  QE_R_RETAKE_SUB: "Participants can try again",
  QE_R_MANUAL_SUB: "Off = Quizoma marks automatically",
  QE_R_PARTIAL_SUB: "Share points on multiple-correct questions",
  QE_R_RAPID_SUB: "Extra points for quick answers",
  QE_READING_TIME: "Reading time",
  QE_CHANGED_TO: "Changed to {type}",
  QE_Q_LIMIT: "{n} questions is the limit",
  QE_DUPLICATED: "Question duplicated",
  QE_DELETED: "Question deleted",
  QE_RAIL_DELETE: "Delete question {n}",
  QE_DEL_CONFIRM_TITLE: "Delete question {n}?",
  QE_DEL_CONFIRM_BODY: "“{text}” will be removed from this quiz. You can undo it right after.",
  QE_DEL_CONFIRM_BODY_EMPTY: "This empty question will be removed from the quiz. You can undo it right after.",
  QE_MOVED: "Question moved to {n}",
  QE_FILLED: "{n} options filled",
  QE_FILLED_Q: "Question + {n} options filled",
  QE_AUTOSAVES: "Quizoma saves every change automatically",
  QE_K_WRITING: "Writing",
  QE_K_LIST: "Questions list",
  QE_K_GENERAL: "General",
  QE_K_NEW_OPTION: "New option",
  QE_K_NEXT: "Next question",
  QE_K_TYPE: "Change question type",
  QE_K_PASTE: "Paste a list into an option",
  QE_K_PICK: "Pick a type (in menu)",
  QE_K_MOVE: "Move question up / down",
  QE_K_UNDO: "Undo",
  QE_K_REDO: "Redo",
  QE_K_SHOW: "Show shortcuts",
  QE_K_CLOSE: "Close menu / panel",
  QE_K_FOOT_A: "Press",
  QE_K_FOOT_B: "anytime to open this",
  QE_LIVE: "Your quiz is live!",
  QE_LIVE_SUB_ONE: " · 1 question",
  QE_LIVE_SUB_MANY: " · {n} questions",
  QE_SHARE_CODE: "SHARE THIS CODE WITH YOUR PARTICIPANTS",
  QE_COPY_CODE: "Copy code",
  QE_COPIED: "Copied ✓",
  QE_COPY_MSG: "Copy invite message",
  QE_MSG_COPIED: "Message copied ✓",
  QE_WHATSAPP: "WhatsApp",
  QE_INVITE: "Join my quiz “{title}” on Quizoma. Code: {code}",
  QE_STAY: "Stay here",
  QE_GO_DASH: "Go to dashboard →",
  QE_PUBLISHED_LABEL: "Quiz published",
  QE_LOCKED: "People have already joined or taken this quiz, so it can't change now.",
  QE_RESULTS: "Results",

  // ── Errors ──
  ERR_GENERIC: "Something went wrong. Please try again.",
  ERR_LOAD_FAILED: "Couldn't load that. Check your connection and try again.",
  ERR_SAVE_FAILED: "Couldn't save. Check your connection and try again.",

  // ── Send feedback (/feedback/) — the app's Feedback screen, without the Play Store hand-off ──
  FB_TITLE: "Send feedback",
  FB_HERO_TITLE: "How's Quizoma working for you?",
  FB_HERO_SUB: "Tell us what's working, what's not, and what you wish it could do.",
  FB_NOTE_TITLE: "Quizoma is free — and your feedback keeps us going",
  FB_NOTE_BODY: "Every message you send motivates us to keep improving it. So please be honest: if something is broken or confusing, or there's a feature you'd love to have, tell us here.",
  FB_RATING_LABEL: "Your rating (optional)",
  FB_RATING_NONE: "No rating needed — you can just write a suggestion.",
  FB_RATING_1: "Not good",
  FB_RATING_2: "Could be better",
  FB_RATING_3: "It's okay",
  FB_RATING_4: "Pretty good",
  FB_RATING_5: "Love it",
  FB_STAR_ONE: "1 star",
  FB_STAR_MANY: "{n} stars",
  FB_CLEAR_RATING: "Clear rating",
  FB_CATEGORY_LABEL: "What's it about?",
  FB_CAT_BUG: "Bug",
  FB_CAT_CRASH: "Crash",
  FB_CAT_SYNC: "Sync / Login",
  FB_CAT_UI_UX: "Design",
  FB_CAT_PERFORMANCE: "Performance",
  FB_CAT_FEATURE_REQUEST: "Feature request",
  FB_CAT_REPORT_CONTENT: "Report content",
  FB_CAT_OTHER: "Other",
  FB_MSG_LABEL: "Your message",
  FB_PH_DEFAULT: "Tell us what's on your mind…",
  FB_PH_BUG: "What happened, and what did you expect to happen?",
  FB_PH_FEATURE: "What would you like to do that you can't today?",
  FB_PH_REPORT: "What's wrong with it, and where did you see it?",
  FB_ERR_PICK_CATEGORY: "Pick a category first.",
  FB_ERR_MORE_DETAIL: "Add a little more detail (at least 5 characters).",
  FB_ERR_SEND_FAILED: "Couldn't send feedback. Check your connection and try again.",
  FB_SEND: "Send feedback",
  FB_THANKS_TITLE: "Thank you!",
  FB_THANKS_BODY: "Your feedback reached us. We read every message, and when we reply you'll see it below.",
  FB_BACK_DASH: "Back to dashboard",
  FB_COOLDOWN_TITLE: "Thanks for your feedback",
  FB_COOLDOWN_BODY: "You can send more in {time}. Until then, your earlier messages and our replies are below.",
  FB_HISTORY_TITLE: "Your feedback",
  FB_FILTER_ALL: "All",
  FB_FILTER_SUGGESTIONS: "Suggestions",
  FB_FILTER_LABEL: "Filter your feedback",
  FB_EMPTY: "No feedback sent yet — share your first thought above.",
  FB_EMPTY_FILTERED: "No {n}-star feedback yet.",
  FB_EMPTY_SUGGESTIONS: "No suggestions yet.",
  FB_SUGGESTION_BADGE: "Suggestion",
  FB_TEAM_REPLY: "Team reply",

  // ── Help & FAQs (/faq/) — the app's FAQ, written for the browser (the Q&A text is in faq/faq-data.js) ──
  FAQ_TITLE: "Help & FAQs",
  FAQ_HERO_TITLE: "How can we help?",
  FAQ_HERO_SUB: "Everything about building, sharing and marking quizzes in Studio — search it, or browse by topic.",
  FAQ_SEARCH_PH: "Search help — e.g. “share code”",
  FAQ_SEARCH_LABEL: "Search the help",
  FAQ_KEY_HINT: "Press / to search",
  FAQ_COUNT_ALL: "{n} answers in {c} topics",
  FAQ_COUNT_ONE: "1 answer found",
  FAQ_COUNT_MANY: "{n} answers found",
  FAQ_CLEAR: "Clear search",
  FAQ_POPULAR: "Popular",
  FAQ_TOPICS: "Topics",
  FAQ_TOPICS_LABEL: "Help topics",
  FAQ_N_QUESTIONS: "{n} questions",
  FAQ_EXAMPLE: "Example",
  FAQ_COPY_LINK: "Copy link to this answer",
  FAQ_LINK_COPIED: "Link to this answer copied",
  FAQ_EXPAND_ALL: "Expand all",
  FAQ_COLLAPSE_ALL: "Collapse all",
  FAQ_NO_RESULTS: "No results for “{q}”",
  FAQ_NO_RESULTS_HINT: "Try a different word, or browse by topic.",
  FAQ_NO_RESULTS_ASK: "Can't find it? Tell us what you were looking for and we'll add it.",
  FAQ_STILL_STUCK: "Still stuck?",
  FAQ_STILL_BODY: "Tell us what you were trying to do. Quizoma is free, and your questions and feedback shape what we build next.",
  FAQ_USER_GUIDE: "User guide",
  FAQ_SUPPORT: "Support",
  ERR_NOT_FOUND: "Quiz not found",
  ERR_NOT_FOUND_BODY: "It may have been deleted, or it belongs to another account.",

  // ── Grading suite (grading/, design-reference/grading.html) ──
  GX_SEP: " · ",
  GX_SUITE_LABEL: "Grading suite",
  GX_WEB: "Web",
  GX_ANDROID: "Android",
  // Stored draft marks dropped on load: those answers were marked in the app or another tab after them.
  GX_MARKED_ELSEWHERE: "Some answers were marked elsewhere since. Your unsent marks for them were dropped.",
  GX_MIN_AGO: "{n} min ago",
  GX_H_AGO: "{n} h ago",
  GX_CHARS: "{n} / {max}",
  GX_T_SINGLE: "Single choice",
  GX_T_MULTI: "Multiple correct",
  GX_T_TF: "True / False",
  GX_T_WRITTEN: "Written",
  GX_T_BLANKS: "Fill in the blank",
  GX_T_POLL: "Poll",
  GX_FC_WELL: "Well explained",
  GX_FC_PARTLY: "Partly correct",
  GX_FC_INCOMPLETE: "Incomplete",
  GX_FC_SPELLING: "Check spelling",
  GX_FC_OFFTOPIC: "Off topic",
  GX_KEY_SPACE: "Space",
  GX_KEY_ENTER: "Enter",
  GX_KEY_ESC: "Esc",
  GX_KEY_CTRL: "Ctrl",
  GX_KEY_ALT: "Alt",
  GX_FILE_FALLBACK: "Quiz",
  // home
  GX_HOME_EMPTY: "Submissions will show up here once participants finish a quiz.",
  GX_GO_DASHBOARD: "Go to dashboard",
  GX_EMPTY_TITLE: "No submissions yet",
  GX_EMPTY_BODY: "When participants finish your quizzes, their answers land here for marking and review.",
  GX_STEP_1: "Share your quiz",
  GX_STEP_1_HINT: "Send the link or room code",
  GX_STEP_2: "Participants submit",
  GX_STEP_2_HINT: "Answers arrive in real time",
  GX_STEP_3: "Mark them here",
  GX_STEP_3_HINT: "Rapid Grade or one by one",
  GX_YOUR_QUIZZES: "YOUR QUIZZES",
  GX_N_ANSWERS_ONE: "{n} answer",
  GX_N_ANSWERS_MANY: "{n} answers",
  GX_LEAD_WAITING_ONE: "{verb} waiting for your marks across {n} quiz.",
  GX_LEAD_WAITING_MANY: "{verb} waiting for your marks across {n} quizzes.",
  GX_IS: "is",
  GX_ARE: "are",
  GX_LEAD_ALL_DONE: "Everything is marked. Nice work.",
  GX_LEAD_UNSENT_ONE: "{n} change isn't submitted yet, so participants won't see it until you submit.",
  GX_LEAD_UNSENT_MANY: "{n} changes aren't submitted yet, so participants won't see them until you submit.",
  GX_STAT_TO_MARK_TIP: "Answers waiting for you to mark by hand. Auto-marked answers never count here, even if you changed them.",
  GX_STAT_TO_MARK: "TO MARK",
  GX_STAT_ANSWER: "answer",
  GX_STAT_ANSWERS: "answers",
  GX_STAT_SUBMISSIONS: "SUBMISSIONS",
  GX_STAT_FROM_STUDENTS: "from participants",
  GX_STAT_QUIZZES: "QUIZZES",
  GX_STAT_NEED_MARKING: "need marking",
  GX_SEC_NEEDS: "NEEDS MARKING",
  GX_SEC_DONE: "ALL MARKED",
  GX_ROW_SUBMITTED_ONE: "{n} submitted",
  GX_ROW_SUBMITTED_MANY: "{n} submitted",
  GX_ROW_QUESTIONS_ONE: "{n} question",
  GX_ROW_QUESTIONS_MANY: "{n} questions",
  GX_ROW_TO_MARK_ONE: "{n} answer to mark",
  GX_ROW_TO_MARK_MANY: "{n} answers to mark",
  GX_ROW_ALL_MARKED: "All answers marked ✓",
  GX_RING_TITLE: "{d} of {tot} marked",
  GX_START_RAPID: "Start Rapid Grade",
  GX_OPEN: "Open",
  GX_REVIEW_MARKS: "Review marks",
  GX_DOWNLOAD_REPORTS: "Download reports",
  GX_DOWNLOAD_FOR: "Download reports for {title}",
  // top bar
  GX_MODE_LABEL: "Grading mode",
  GX_MODE_RAPID: "Rapid Grade",
  GX_MODE_BYQ: "By question",
  GX_MODE_IND: "By participant",
  GX_PROG_OF: " of ",
  GX_PROG_MARKED: " answers marked",
  GX_PROG_AUTO: "Auto-marked · nothing to mark",
  GX_SUBMIT_MARKS: "Submit marks",
  GX_SUBMIT_MARKS_TITLE: "Marks stay a draft until you submit them",
  GX_SUBMIT: "Submit",
  GX_SUBMIT_TITLE_ONE: "Submit {n} mark?",
  GX_SUBMIT_TITLE_MANY: "Submit {n} marks?",
  // The Submit confirm — the app's SubmitMarksDialog, same words (webtest/text-parity.test.mjs).
  GRADE_SUBMIT_CONFIRM: "Yes, submit",
  GRADE_SUBMIT_BADGE: "Participants are notified",
  GRADE_SUBMIT_BODY_ONE: "{n} participant will get a notification that their marks were updated. Are you sure you want to submit?",
  GRADE_SUBMIT_BODY_MANY: "{n} participants will get a notification that their marks were updated. Are you sure you want to submit?",
  // Results hidden (Show Score off, not released yet): submitting notifies nobody.
  GRADE_SUBMIT_BADGE_HIDDEN: "Results are hidden",
  GRADE_SUBMIT_BODY_HIDDEN_MANUAL: "Show Score & Result is off for this quiz, so participants won't be notified yet. They'll see these marks when you announce results.",
  GRADE_SUBMIT_BODY_HIDDEN_AUTO_END: "Show Score & Result is off for this quiz, so participants won't be notified yet. They'll see these marks when the quiz ends.",
  GRADE_SUBMIT_BODY_HIDDEN_AUTO_NO_END: "Show Score & Result is off for this quiz, so participants won't be notified yet. They'll see these marks when you end the quiz.",
  // Show Score off but already released: a paper with answers still to mark stays hidden.
  GRADE_SUBMIT_BODY_RELEASED: "Participants whose answers are all marked will be notified and can see their marks. Anyone with answers still to mark hears once you finish their paper.",
  // "Notify participants" (results visible): off = submitted quietly, no notification.
  GRADE_SUBMIT_NOTIFY: "Notify participants",
  GRADE_SUBMIT_NOTIFY_HINT: "Send a notification that their marks changed. Your choice is remembered.",
  GRADE_SUBMIT_BADGE_QUIET: "No notification",
  GRADE_SUBMIT_BODY_QUIET: "Marks will be updated without a notification. Participants see them the next time they open their result.",
  // Results hidden: what happens to them after submitting. Keep hidden is always the default.
  GRADE_SUBMIT_RELEASE_LABEL: "After submitting",
  GRADE_SUBMIT_RELEASE_KEEP_HIDDEN: "Keep results hidden",
  GRADE_SUBMIT_RELEASE_ANNOUNCE: "Announce results",
  GRADE_SUBMIT_RELEASE_FAILED: "Marks submitted, but results weren't announced. Try Announce from the quiz.",
  GX_SUBMITTED_ONE: "Marks sent to {n} participant",
  GX_SUBMITTED_MANY: "Marks sent to {n} participants",
  GX_SUBMIT_FAILED_ONE: "Couldn't send marks for {n} participant. They're kept as a draft — check your connection and submit again.",
  GX_SUBMIT_FAILED_MANY: "Couldn't send marks for {n} participants. They're kept as a draft — check your connection and submit again.",
  GX_LEAVE_TITLE_ONE: "{n} mark not submitted",
  GX_LEAVE_TITLE_MANY: "{n} marks not submitted",
  GX_LEAVE_BODY: "Participants only see marks after you submit them. Keep them as a draft to finish later, or submit now.",
  GX_LEAVE_SUBMIT: "Submit now",
  GX_LEAVE_KEEP: "Keep as draft",
  GX_LEAVE_DISCARD: "Discard",
  GX_DISCARDED: "Draft marks discarded",
  GX_NOT_SUBMITTED_ONE: "{n} not submitted",
  GX_NOT_SUBMITTED_MANY: "{n} not submitted",
  GX_REPORT: "Report",
  GX_KB_TITLE: "Keyboard shortcuts",
  GX_KB_BTN_TITLE: "Keyboard shortcuts (?)",
  GX_KB_HEAD_MODE: "Shortcuts · {mode}",
  GX_KB_TOGGLE: "Show / hide shortcuts",
  GX_UNDO_TITLE: "Undo last mark (Z)",
  GX_KB_FULL: "Full marks",
  GX_KB_HALF: "Half marks",
  GX_KB_ZERO: "Zero",
  GX_KB_EXACT: "Exact mark (questions up to 10 pts)",
  GX_KB_COMMENT: "Add a comment",
  GX_KB_SAVE_NEXT: "Next participant",
  GX_KB_PREV_NEXT: "Previous / next participant",
  GX_KB_PREV_NEXT_Q: "Previous / next question",
  GX_KB_EVERYWHERE: "Everywhere",
  GX_KB_UNDO: "Undo last mark",
  GX_KB_SWITCH: "Switch mode",
  GX_KB_CLOSE: "Close / cancel",
  GX_KB_OR: " or ",
  GX_KB_PLUS: " + ",
  GX_NOTHING_UNDO: "Nothing to undo",
  GX_SHEET_CHANGED: "A participant retook this quiz, so their answers were reloaded.",
  // rapid
  GX_F_UNMARKED: "Unmarked",
  GX_F_TYPED: "Typed answers",
  GX_F_COMMON: "Common answers",
  GX_F_ALL: "All answers",
  GX_CARD: "Card ",
  GX_CARD_OF: " of ",
  GX_CARD_LEFT: " · {n} left",
  GX_LG_FULL: " Full",
  GX_LG_HALF: " Half",
  GX_LG_ZERO: " Zero",
  GX_LG_EXACT: " Exact",
  GX_LG_COMMENT: " Comment",
  GX_LG_UNDO: " Undo",
  GX_GROUP_OPTIONS: "Group options",
  GX_GROUP_N: "👥 {n} participants",
  GX_DISSOLVE: "Split into separate cards",
  GX_EXCLUDE_HEAD: "TAKE SOMEONE OUT",
  GX_SPLIT_BTN: "Split",
  GX_GROUP_HINT: "Same answers share one card and one mark. Split to mark each participant on their own.",
  GX_TIP_GROUP: "{n} participants gave this same answer, so one mark goes to all of them. Click to split or take someone out.",
  GX_TIP_SPLIT: "Give each of these {n} participants their own card",
  GX_TIP_TAKE_OUT: "{name} gets their own card, right after this one",
  GX_TIP_TAKE_OUT_BQ: "{name} gets their own card",
  GX_TIP_PUT_BACK: "Put back in the group",
  GX_EXCLUDE: "Exclude",
  GX_PLAT_SUBMITTED: "{plat} · submitted {when}",
  GX_SUBMITTED_CAP: "Submitted {when}",
  GX_Q_TYPE: "Q{n} · {type}",
  GX_PTS_ONE: "{n} pt",
  GX_PTS_MANY: "{n} pts",
  GX_NO_ANSWER: "No answer given",
  GX_NOW: "Now {x}/{max}",
  GX_CLOSE: "Close to expected ",
  GX_AUTO_MARKED: "Auto-marked: ",
  GX_CORRECT: "correct",
  GX_WRONG: "wrong",
  GX_YOU_CAN_OVERRIDE: " · you can override",
  GX_THEIR_ANSWER: "THEIR ANSWER",
  GX_STUDENT_ANSWER: "PARTICIPANT'S ANSWER",
  GX_EXPECTED: "EXPECTED",
  GX_CORRECT_ANSWER: "CORRECT ANSWER",
  GX_EXACT_MARK: "Exact mark",
  GX_EXACT_TITLE: "Type an exact mark",
  GX_MARK: "Mark",
  GX_OUT_OF: "/ {max}",
  GX_ADD_COMMENT: "Add comment",
  GX_EDIT_COMMENT: "Edit comment",
  GX_COMMENT_LABEL: "Comment",
  GX_NOTE_FOR_GROUP: "Note for these {n} participants (they see it with their result)",
  GX_NOTE_FOR_ONE: "Note for {name} (they see it with their result)",
  GX_SAVE_NOTE: "Save note",
  GX_QUOTE: "“{text}”",
  GX_ONE_MARK_ALL: "One mark goes to all {n}",
  GX_ALL_MARKED: "All submissions marked!",
  GX_READY_EXPORT: "Ready to export results or share with everyone.",
  GX_VIEW_CHART: "View results chart",
  GX_REVIEW_BY_STUDENT: "Review by participant",
  GX_MARK_AGAIN: "Mark again",
  GX_REMARK_TITLE: "Marking again",
  GX_REMARK_BODY: "Every answer is already marked. New marks replace the old ones.",
  GX_REMARK_DONE: "Done",
  GX_END_STUDENTS_ONE: "participant",
  GX_END_STUDENTS_MANY: "participants",
  GX_END_ANSWERS_ONE: "answer marked",
  GX_END_ANSWERS_MANY: "answers marked",
  GX_END_QUESTIONS_ONE: "question",
  GX_END_QUESTIONS_MANY: "questions",
  GX_END_LIST: "End of this list",
  GX_STILL_WAITING_ONE: "{n} answer is still waiting in other lists.",
  GX_STILL_WAITING_MANY: "{n} answers are still waiting in other lists.",
  GX_GO_UNMARKED: "Go to unmarked",
  GX_LAST: "Last: ",
  GX_SPLIT: "Group split into {n} cards",
  GX_EXCLUDED: "{name} will be marked on their own, next",
  GX_COMMENT_SAVED: "Comment saved",
  GX_COMMENT_REMOVED: "Comment removed",
  GX_ENTER_RANGE: "Enter 0 to {max}",
  GX_OUT_OF_MAX: "This question is out of {max}",
  GX_NO_HALF: "A {max}-point question has no half mark",
  GX_N_STUDENTS: "{n} participants",
  GX_X_OF_MAX: "{x}/{max}",
  GX_STAMP_FULL: "FULL",
  GX_STAMP_ZERO: "ZERO",
  GX_STAMP_HALF: "HALF",
  GX_STAMP_X: "{x} / {max}",
  // by question
  GX_QUESTIONS: "Questions",
  GX_NO_QUESTIONS: "This quiz has no questions to mark",
  GX_ALL_MARKED_TIP: "All marked",
  GX_Q_TYPE_PTS: "Q{n} · {type} · {pts}",
  GX_EXPECTED_LABEL: "Expected: ",
  GX_CORRECT_LABEL: "Correct: ",
  GX_AUTO_OVERRIDE: " · auto-marked, you can override",
  GX_BQ_PREV: "Previous",
  GX_BQ_NEXT: "Next",
  GX_BQ_POS: "{n} of {total}",
  GX_BQ_NEXT_TO_MARK: "Next to mark",
  GX_BQ_NEXT_Q: "Next question",
  GX_BQ_DONE: "Everything on this question is marked",
  GX_BQ_AUTO_DONE: "Auto-marked. Change any mark you disagree with",
  GX_BQ_LG_PEND: "left to mark",
  GX_BQ_LG_DONE: "nothing to mark",
  GX_BQ_LG_CHANGED: "changed, not submitted",
  GX_BQ_LG_UNSEEN: "not opened yet",
  GX_BQ_GROUP_TIP: "Split this group or take someone out",
  GX_BQ_SPLIT_ALL: "Split into separate cards",
  GX_BQ_TAKE_OUT: "TAKE SOMEONE OUT",
  GX_BQ_TOOK_OUT: "{name} now has their own card",
  GX_BQ_PUT_BACK: "Put back",
  GX_BQ_REGROUPED: "Back in the group",
  GX_BQ_ST_ANSWERED: "participants answered",
  GX_BQ_ST_ANSWERED_TIP: "How many participants answered this question",
  GX_BQ_ST_DIFFERENT: "different answers",
  GX_BQ_ST_DIFFERENT_TIP: "Participants who gave the same answer share one card",
  GX_BQ_ST_LEFT: "left to mark",
  GX_BQ_ST_LEFT_TIP: "Answers on this question still waiting for a mark",
  // polls beside the marking
  GX_POLL_PILL: "Poll · Q{n} · no marks",
  GX_POLL_ANON: "Anonymous",
  GX_POLL_VOTED_ONE: "{n} vote",
  GX_POLL_VOTED_MANY: "{n} votes",
  GX_POLLS_TITLE: "Polls in this quiz",
  GX_POLLS_HEAD_ONE: "{n} poll in this quiz",
  GX_POLLS_HEAD_MANY: "{n} polls in this quiz",
  GX_POLL_NOT_COUNTED: "Polls have no marks and aren't in any total.",
  GX_POLL_CHIP_ONE: "{n} Poll",
  GX_POLL_CHIP_MANY: "{n} Polls",
  GX_POLL_CHIP_TITLE: "See the votes on this quiz's polls",
  GX_POLL_ONLY_TITLE: "This quiz only has polls",
  GX_POLL_ONLY_BODY: "Polls have no marks, so there's nothing to grade. Here are the votes.",
  GX_POLL_FULL_RESULTS: "Open full results",
  GX_ROW_POLLS_ONE: "{n} poll",
  GX_ROW_POLLS_MANY: "{n} polls",
  GX_ROW_POLLS_ONLY: "Polls only · nothing to mark",
  GX_VIEW_POLL_RESULTS: "View poll results",
  // by student progress
  GX_IND_PROG: " of {n} participants fully marked",
  GX_IND_UNSENT_ONE: "{n} change not submitted · Submit",
  GX_IND_UNSENT_MANY: "{n} changes not submitted · Submit",
  GX_IND_ALL_DONE: "Everyone is marked",
  GX_ST_ANSWERS: "answers",
  GX_ST_DIFFERENT: "different",
  GX_ST_TO_MARK: "to mark",
  GX_NOT_MARKED: "Not marked",
  GX_X_OF_N_MARKED: "{x} of {n} marked",
  GX_MIXED: "Mixed marks",
  GX_EACH: "{x} / {max} each",
  GX_COUNT: "👥 {n}",
  GX_N_MORE: "+{n} more",
  GX_AUTO_VERDICT: "Auto: {v}",
  GX_AUTO_CHANGED: "Auto: {v} · changed by you",
  GX_FULL_N: "Full {max}",
  GX_HALF: "Half",
  GX_EXACT_GROUP: "Exact mark for this group",
  GX_NOTE_LABEL: "Note",
  GX_SAME_NOTE: "Same note for all {n} (optional)",
  GX_NOTE_ONE: "Note for this participant (optional)",
  GX_SAVE: "Save",
  GX_GIVEN_TO_ONE: "{n} participant",
  GX_GIVEN_TO_MANY: "{n} participants",
  GX_X_GIVEN: "{x}/{max} given to {to}",
  GX_NOTE_SAVED_N: "Note saved for {n}",
  GX_NOTE_REMOVED: "Note removed",
  // by student
  GX_R_ALL: "All",
  GX_R_NEED: "Needs marking",
  GX_R_DONE: "Graded",
  GX_R_NONE: "Not started",
  GX_SEARCH_STUDENTS: "Search participants",
  GX_NOT_STARTED_YET: "Not started yet",
  GX_NO_STUDENTS_HERE: "No participants here",
  GX_TRY_FILTER: "Try another filter.",
  GX_SCORE: "{g} / {m}",
  GX_N_TO_MARK: "{n} to mark",
  GX_GRADED: "Graded",
  GX_PICK_STUDENT: "Pick a participant",
  GX_BACK_STUDENTS: "‹ Participants",
  GX_SUBMITTED_WHEN_SEP: "Submitted {when} · ",
  GX_HAS_NOT_STARTED: "Has not started this quiz",
  GX_OF_PTS: "/ {m} pts",
  GX_DL_STUDENT_TITLE: "Download {name}'s report",
  GX_DL_STUDENT_LABEL: "Download {name}'s report",
  GX_PREVIOUS: "‹ Previous",
  GX_I_OF_N: "{i} of {n}",
  GX_SAVE_NEXT: "Next participant",
  GX_NOTHING_YET: "Nothing to mark yet",
  GX_NOT_STARTED_BODY: "{name} hasn't started. You'll see their answers here once they submit.",
  GX_OVERALL_PH: "Overall feedback they see with their result",
  GX_OVERALL_FOR: "Note for {name}, whole quiz",
  GX_NOTE_FOR: "Note for {name}",
  GX_WHOLE_QUIZ: "· whole quiz, optional",
  GX_NEEDS_MARKING: "Needs marking",
  GX_V_FULL: "✓ {x}/{max}",
  GX_V_ZERO: "✕ 0/{max}",
  GX_CHANGED_BY_YOU: "Changed by you",
  GX_AUTO_MARKED_LBL: "Auto-marked",
  GX_ANSWER: "ANSWER",
  GX_NOTE_ANSWER_PH: "Note for this answer (optional)",
  GX_QUICK_MARKS: "Quick marks",
  GX_LESS: "Less",
  GX_MORE: "More",
  GX_MARKS: "Marks",
  GX_SAVED_TOAST: "Kept as a draft · Submit marks when you're done",
  GX_SAVED_LEFT_ONE: "Kept as a draft · {n} answer still unmarked for {name}",
  GX_SAVED_LEFT_MANY: "Kept as a draft · {n} answers still unmarked for {name}",
  // celebration
  GX_SCORES_OF: "SCORES · {title}",
  GX_BAND: "{lo}–{hi}%",
  GX_AVERAGE: "average",
  GX_HIGHEST: "highest",
  GX_STUDENTS: "participants",
  GX_EXPORT_RESULTS: "Export results",
  GX_SHARE_CLASS: "Share with everyone",
  GX_SHARE_SOON: "Sharing results with everyone isn't on the web yet. Use Export results for now.",
  // download reports
  GX_PREVIEW: "PREVIEW",
  GX_WHO_FOR: "WHO IS IT FOR",
  GX_WHO: "Who",
  GX_SC_CLASS: "Everyone",
  GX_SC_CLASS_D_ONE: "All {n} participant",
  GX_SC_CLASS_D_MANY: "All {n} participants",
  GX_SC_SOME: "Pick participants",
  GX_SC_SOME_D: "{n} selected",
  GX_SC_SOME_D0: "Choose a few",
  GX_SC_ONE: "One participant",
  GX_SC_ONE_D: "A single report card",
  GX_STUDENTS_H: "PARTICIPANTS",
  GX_STUDENT_H: "PARTICIPANT",
  GX_X_OF_N: "{x} of {n}",
  GX_SELECT_ALL: "Select all",
  GX_CLEAR_ALL: "Clear all",
  GX_N_UNMARKED: "{n} unmarked",
  GX_NO_MATCH: "No match",
  GX_WHAT: "WHAT TO INCLUDE",
  GX_REPORT_TYPE: "Report type",
  GX_K_SUM: "Group summary",
  GX_K_SUM_D: "One sheet: scores table + chart",
  GX_K_CMP: "Compare participants",
  GX_K_CMP_D: "Side by side, question by question",
  GX_K_CARDS: "Report cards",
  GX_K_CARDS_D: "One page for each participant",
  GX_K_BOTH: "Summary + cards",
  GX_K_BOTH_D: "Summary first, then report cards",
  GX_K_CARD: "Report card",
  GX_K_CARD_D: "Score, every answer and your notes",
  GX_FORMAT: "FORMAT",
  GX_FMT_PDF: "PDF · ready to print",
  GX_FMT_XLSX: "Excel sheet",
  GX_FMT_CSV: "CSV",
  GX_OPTIONS: "OPTIONS",
  GX_OPT_ANS: "Show answers",
  GX_OPT_ANS_D: "Each participant's answer next to the right one",
  GX_OPT_NOTES: "Include your notes",
  GX_OPT_NOTES_D: "Per-answer notes and the whole-quiz note",
  GX_OPT_CHART: "Score chart",
  GX_OPT_CHART_D: "On the group summary and comparison",
  GX_RP_WARN_ONE: "{n} answer still unmarked. It'll show as “Not marked yet”.",
  GX_RP_WARN_MANY: "{n} answers still unmarked. They'll show as “Not marked yet”.",
  GX_FINISH_MARKING: "Finish marking",
  GX_PICK_1: "Pick at least one participant",
  GX_PICK_2: "Pick at least 2 participants to compare",
  GX_PICK_2_A: "Pick at least 2 participants",
  GX_PICK_2_B: "to compare",
  GX_STUDENT_W: " participant",
  GX_STUDENTS_W: " participants",
  GX_PAGE_W: " page",
  GX_PAGES_W: " pages",
  GX_DOWNLOAD: "Download",
  GX_DOWNLOAD_FMT: "Download {fmt}",
  GX_PREPARING: "Preparing…",
  GX_DOWNLOADED: "Downloaded ✓",
  GX_FILE_DOWNLOADED: "{file} downloaded",
  GX_DOWNLOAD_FAILED: "Couldn't make that file. Check your connection and try again.",
  GX_PV_XLSX: "Excel · 1 sheet",
  GX_PV_CSV: "CSV · 1 file",
  GX_PV_SHEET_CAP: "One row per participant, one column per question",
  GX_PV_CMP_CAP: "Best score at the top · colours show full, part, zero marks",
  GX_PAGE_1_OF: "Page 1 of {n}",
  GX_PV_BOTH_CAP: "Group report, then every participant's answers",
  GX_PV_SUM_CAP: "Stats, question accuracy, polls and the participant list",
  GX_PV_CARDS_ONE: "{n} report card, one per page",
  GX_PV_CARDS_MANY: "{n} report cards, one per page",
  // report pages + files
  // report pages in the app's style (ResultPdfGenerator.kt)
  GX_RP_BADGE_CLASS: "QUIZOMA: QUIZ & TEST MAKER · RESULTS REPORT",
  GX_RP_BADGE_ONE: "QUIZOMA: QUIZ & TEST MAKER · RESULT",
  GX_RP_BADGE_CMP: "QUIZOMA: QUIZ & TEST MAKER · PARTICIPANT COMPARISON",
  GX_RP_TEACHER: "Host: {name}",
  GX_RP_GENERATED: "Generated {date}",
  GX_RP_FOOT_BRAND: "Quizoma: Quiz & Test Maker  ·  quizoma.com",
  GX_RP_PAGE_OF: "Page {n} of {total}",
  GX_RP_REPORT: "RESULTS REPORT",
  GX_RP_ST_PARTS: "Participants",
  GX_RP_ST_AVG: "Average score",
  GX_RP_ST_HIGH: "Highest score",
  GX_RP_ST_LOW: "Lowest score",
  GX_RP_ST_PASSED: "Passed (≥60%)",
  GX_RP_ST_AWAIT: "Awaiting marking",
  GX_RP_ST_QUESTIONS: "Questions",
  GX_RP_SEC_DIST: "Score distribution",
  GX_RP_SEC_ACC: "Question accuracy",
  GX_RP_ACC: "ACCURACY",
  GX_RP_SEC_POLLS: "Poll results",
  GX_RP_SEC_PARTS: "Participants ({n})",
  GX_RP_RANK: "RANK",
  GX_RP_SEC_INDIV: "Individual results",
  GX_RP_OWNER_NOTE: "Note from the quiz owner",
  GX_RP_GIVEN: "GIVEN",
  GX_RP_NO_ANSWER: "(no answer)",
  GX_RP_META_SCORE: "Score {g}/{m} ({pct}%)",
  GX_RP_META_RIGHT: "Correct {c}  ·  Wrong {w}",
  GX_RP_META_PART: "Partial {n}",
  GX_RP_META_SKIP: "Skipped {n}",
  GX_RP_DRAFTS_ONE: "Includes {n} change you haven't submitted yet. Participants see it only after you submit.",
  GX_RP_DRAFTS_MANY: "Includes {n} changes you haven't submitted yet. Participants see them only after you submit.",
  GX_RP_SUMMARY: "GROUP SUMMARY",
  GX_RP_COMPARE: "PARTICIPANT COMPARISON",
  GX_RP_CARD: "REPORT CARD",
  GX_RP_AVERAGE: "AVERAGE",
  GX_RP_STUDENT: "PARTICIPANT",
  GX_RP_SCORE: "SCORE",
  GX_RP_STATUS: "STATUS",
  GX_RP_MARKED: "Marked",
  GX_RP_N_NOT_MARKED: "{n} not marked",
  GX_RP_TOP: "TOP SCORE",
  GX_RP_HARDEST: "HARDEST QUESTION",
  GX_RP_COMPARED_ONE: "{n} participant compared",
  GX_RP_COMPARED_MANY: "{n} participants compared",
  GX_RP_HARD_LINE: "avg {avg}% · {text}",
  GX_RP_SCORES: "SCORES",
  GX_RP_CLASS_AVG_MARK: "▲ group avg {avg}%",
  GX_RP_QBYQ: "QUESTION BY QUESTION",
  GX_RP_TOTAL: "TOTAL",
  GX_RP_CLASS_AVG: "Group average",
  GX_RP_LEG_FULL: "Full marks",
  GX_RP_LEG_PART: "Part marks",
  GX_RP_LEG_ZERO: "Zero",
  GX_RP_LEG_PENDING: "Not marked yet",
  GX_RP_QUESTION: "QUESTION",
  GX_RP_CORRECT: "CORRECT",
  GX_RP_MARKS: "MARKS",
  GX_RP_NOTE: "Note: {text}",
  GX_RP_NOT_MARKED: "Not marked",
  GX_RP_COL_RANK: "Rank",
  GX_RP_COL_STUDENT: "Participant",
  GX_RP_COL_SUBMITTED: "Submitted",
  GX_RP_COL_TOTAL: "Total",
  GX_RP_COL_OVERALL: "Overall note",
  GX_RP_COL_ANSWER_SUFFIX: "answer",
  GX_RP_COL_NOTE_SUFFIX: "note",
  GX_RP_PLUS_ANSWERS: "+ an \"Answers\" sheet",
  GX_RP_PLUS_NOTES: "+ a \"Notes\" sheet",
  GX_RP_CSV_EXTRA: " (CSV puts these as extra columns)",
  GX_RP_SHEET_SCORES: "Scores",
  GX_RP_SHEET_ANSWERS: "Answers",
  GX_RP_SHEET_NOTES: "Notes",
  // phone tab bar
  GX_TABS_LABEL: "Main",
  GX_TAB_NEW: "New",
  GX_TAB_MORE: "More",
};

/** Fills {name} placeholders: t(S.QUESTION_N_OF, { n: 3, total: 9 }). */
export function t(template, vars = {}) {
  return String(template).replace(/\{(\w+)\}/g, (whole, key) =>
    Object.prototype.hasOwnProperty.call(vars, key) ? String(vars[key]) : whole
  );
}
